import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createServer} from 'node:http';
import {chromium} from 'playwright';
import {ControlSettings} from '../dist/observability/control-settings.js';
import {prepareLocalConnection} from '../dist/onboarding/connection.js';
import {loadHostConfig} from '../dist/interface/config.js';
import {modelSettingsPath,readModelSettings} from '../dist/onboarding/model-settings.js';

test('runtime native local settings UI desktop/mobile completes wizard, probes provider and masks keys (fixture provider)',async()=>{
  const browser=await chromium.launch({headless:true});await mkdir('tests/evidence/phase58',{recursive:true});
  try{for(const width of [1440,390]){
    const root=await mkdtemp(join(tmpdir(),'driver-settings-ui-')),paths=await prepareLocalConnection(root),config=loadHostConfig(paths.runtimeConfig);
    const auth={async connections(){return [{id:'codex',status:'ready',structured_bridge:true,supported_login_flows:['device'],connection:{client_id:'codex',state:'idle'}}];},view(){return {state:'idle'};},close(){},async start(){throw Error('not used');}};
    let providerCalls=0;const providerFetch=async()=>{providerCalls++;return new Response(JSON.stringify({status:'completed',model:'gpt-5.6-luna',output:[{type:'message',phase:'final_answer',content:[{type:'output_text',text:'{"status":"ok","nonce":"agent-driver-provider-probe"}'}]}],usage:{input_tokens:1,output_tokens:1,total_tokens:2}}),{status:200,headers:{'content-type':'application/json'}});};
    let mcpRegistered=false;const mcp={async view(){const registration=mcpRegistered?'registered':'not_registered';return {agent_driver:{installed:true,mcp_command:'agent-driver mcp'},clients:[{id:'codex',installed:true,registration,automatic:true,reason:registration,restart_required:mcpRegistered}],registered_count:mcpRegistered?1:0,credentials_exposed:false};},async register(id){assert.equal(id,'codex');mcpRegistered=true;return this.view();}};
    const activity=undefined,bootstrap={view(){return {clients:[{id:'codex',label:'Codex',docs_url:'https://learn.chatgpt.com/docs/codex/cli',installer_url:'https://chatgpt.com/codex/install.sh',install_command:'curl -fsSL https://chatgpt.com/codex/install.sh | sh',auth_guide_url:'https://learn.chatgpt.com/docs/auth',installed:true,managed_install:true,reason:'installed',credentials_exposed:false},{id:'claude',label:'Claude Code',docs_url:'https://code.claude.com/docs/en/quickstart',installer_url:'https://claude.ai/install.sh',install_command:'curl -fsSL https://claude.ai/install.sh | bash',auth_guide_url:'https://code.claude.com/docs/en/quickstart',installed:false,managed_install:true,reason:'not_installed',credentials_exposed:false}],credentials_exposed:false};},async install(){throw Error('not used');}};
    const settings=new ControlSettings(config,auth,{},providerFetch,mcp,activity,bootstrap);let host;const server=createServer(async(req,res)=>{if(req.url==='/test/'){res.end('<h1>Control Center</h1>');return;}if(!await settings.handle(req,res,req.url.slice('/test/'.length),host)){res.writeHead(404);res.end();}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));host='127.0.0.1:'+server.address().port;
    const page=await browser.newPage({viewport:{width,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
    try{
      await page.goto('http://'+host+'/test/settings');await page.getByRole('heading',{name:'에이전트 연결',exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Claude Code 설치',exact:true}).count(),1);assert.equal(await page.getByRole('link',{name:'공식 설치 안내',exact:true}).count(),1);await page.screenshot({path:'tests/evidence/phase58/client-bootstrap-'+width+'.png',fullPage:true});await page.getByRole('button',{name:'Codex에 MCP 등록',exact:true}).click();await page.getByText('Codex · MCP 등록됨',{exact:true}).waitFor();await page.getByRole('button',{name:'다음',exact:true}).click();await page.getByRole('heading',{name:'로컬 실행',exact:true}).waitFor();await page.getByRole('button',{name:'로컬 실행 승인',exact:true}).click();await page.getByRole('heading',{name:'AI 연결',exact:true}).waitFor();
      const ai=page.locator('#step-2');await page.getByRole('button',{name:'연결 상태 확인',exact:true}).click();await page.getByText('Codex · 연결됨',{exact:true}).waitFor();await ai.getByLabel('연결 방식',{exact:true}).selectOption('api');await ai.getByLabel('API 키',{exact:true}).fill('fixture-secret-not-real-123456789');await ai.getByRole('button',{name:'저장',exact:true}).click();assert.match(await page.getByRole('status').textContent(),/요금/);assert.equal(readModelSettings(modelSettingsPath(config)),null);
      await ai.getByLabel('API 사용 요금을 확인했습니다.').check();await ai.getByRole('button',{name:'저장',exact:true}).click();await page.getByRole('status').filter({hasText:'저장했습니다'}).waitFor();assert.equal(await ai.getByLabel('API 키',{exact:true}).inputValue(),'');assert.equal(readModelSettings(modelSettingsPath(config)).selection.mode,'api');assert.equal(readModelSettings(modelSettingsPath(config)).api_verification.provider,'openai');
      const tail=await page.locator('#setup-log').textContent();assert.match(tail,/\[MCP\].*Codex MCP 등록을 마쳤습니다/su);assert.match(tail,/\[RUNTIME\].*로컬 실행 연결을 승인했습니다/su);assert.doesNotMatch(tail,/fixture-secret/iu);
      await page.screenshot({path:'tests/evidence/phase58/settings-api-'+width+'.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
      await page.reload();await page.getByRole('heading',{name:'AI 연결',exact:true}).waitFor();assert.equal(await ai.getByLabel('연결 방식',{exact:true}).inputValue(),'api');await ai.getByLabel('연결 방식',{exact:true}).selectOption('subscription');await ai.getByRole('button',{name:'다음',exact:true}).click();await page.getByRole('heading',{name:'Jev 연결',exact:true}).waitFor();assert.equal(await page.getByText('4 / 4',{exact:true}).count(),1);assert.equal(await page.getByRole('button',{name:'사이트',exact:true}).count(),0);const jev=page.locator('#step-3');await jev.getByLabel('사용 방식',{exact:true}).selectOption('off');await jev.getByRole('button',{name:'완료',exact:true}).click();await page.getByRole('heading',{name:'Control Center'}).waitFor();
      const saved=readModelSettings(modelSettingsPath(config));assert.equal(saved.onboarding_step,4);assert.equal(saved.selection.mode,'subscription');assert.equal(saved.selection.jev,'off');assert.equal(providerCalls,1);assert.deepEqual(errors,[]);
    }finally{await page.close();settings.close();await new Promise(resolve=>server.close(resolve));await rm(root,{recursive:true,force:true});}
  }}finally{await browser.close();}
});
