import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {RuntimeStore} from '../dist/store/runtime-store.js';
import {Runtime} from '../dist/core/runtime.js';
import {browserResource,guard} from '../dist/policy/dispatch-guard.js';
import {chooseRoute,modelExecutionPermission} from '../dist/policy/routes.js';
import {FIXTURE_DRAFT} from '../dist/browser/fixture-driver.js';
async function setup(t){const root=await mkdtemp(join(tmpdir(),'agent-driver-test-')),db=join(root,'state.sqlite'),store=new RuntimeStore(db);t.after(async()=>{try{store.close();}catch{}await rm(root,{recursive:true,force:true});});const project={id:'p',callerRef:'owner',worktree:root,profileRef:'own-profile',accountRef:'a',allowedOrigins:['http://127.0.0.1:9000'],capabilities:[FIXTURE_DRAFT.id]};store.registerProject(project);const task=store.createTask('p',FIXTURE_DRAFT.id),lease=store.acquire(task.id,browserResource(project),'target');return {root,db,store,project,task,lease};}
function observation(x,change={}){return {targetRef:'target',targetExists:true,ownerTaskId:x.task.id,projectId:'p',profileRef:'own-profile',accountRef:'a',origin:'http://127.0.0.1:9000',generation:x.lease.generation,observedMonoMs:performance.now(),visibility:'visible',environment:'owned_headless',...change};}
function verifier(x,result='MATCH'){return {result,source:'independent_test_readback',accountRef:'a',targetRef:'target',generation:x.lease.generation,observedMonoMs:performance.now(),detail:{}};}
test('runtime native SQLite uses WAL/FULL and persists tasks and event delivery across reopen',async t=>{const x=await setup(t);assert.deepEqual(x.store.durability(),{journal_mode:'wal',synchronous:2});const events=x.store.events('p','consumer');assert.ok(events.length>=2);x.store.close();const second=new RuntimeStore(x.db);try{assert.equal(second.task(x.task.id).status,'running');assert.deepEqual(second.events('p','consumer').map(e=>e.id),events.map(e=>e.id));assert.throws(()=>second.ack('p','consumer',events.at(-1).id+100),/INVALID_ACK/);second.ack('p','consumer',events.at(-1).id);assert.equal(second.events('p','consumer').length,0);}finally{second.close();}});
test('runtime contract rejects caller/account/target/generation/origin/foreground before any dispatch',async t=>{const x=await setup(t);const context={taskId:x.task.id,callerRef:'owner',lease:x.lease,capability:FIXTURE_DRAFT,observation:observation(x),maxObservationAgeMs:3000};guard(x.store,context);for(const changed of [{callerRef:'stranger'},{observation:observation(x,{accountRef:'b'})},{observation:observation(x,{targetExists:false})},{observation:observation(x,{generation:999})},{observation:observation(x,{origin:'https://example.com'})},{capability:{...FIXTURE_DRAFT,requiresOsInput:true}},{observation:observation(x,{observedMonoMs:performance.now()+10000})}])assert.throws(()=>guard(x.store,{...context,...changed}));let effects=0;const runtime=new Runtime(x.store,[FIXTURE_DRAFT]);await assert.rejects(runtime.execute(x.task.id,'stranger',x.lease,FIXTURE_DRAFT.route,{}, {observe:async()=>observation(x),execute:async()=>{effects++;},verify:async()=>verifier(x)}));assert.equal(effects,0);});
test('runtime native lease fencing blocks an old writer and does not take over unresolved effects',async t=>{const x=await setup(t);x.store.release(x.lease);const next=x.store.createTask('p',FIXTURE_DRAFT.id),lease=x.store.acquire(next.id,browserResource(x.project),'next');assert.ok(lease.generation>x.lease.generation);assert.throws(()=>x.store.begin(x.lease,FIXTURE_DRAFT.id,'write_external',{},FIXTURE_DRAFT.route),/STALE_FENCE/);x.store.begin(lease,FIXTURE_DRAFT.id,'write_external',{},FIXTURE_DRAFT.route);assert.throws(()=>x.store.release(lease),/UNRESOLVED_INTENT/);const other=x.store.createTask('p',FIXTURE_DRAFT.id);assert.throws(()=>x.store.acquire(other.id,browserResource(x.project),'other'),/RESOURCE_BUSY/);});
test('runtime contract successful response without independent evidence never succeeds',async t=>{const x=await setup(t);let count=0;const result=await new Runtime(x.store,[FIXTURE_DRAFT]).execute(x.task.id,'owner',x.lease,FIXTURE_DRAFT.route,{}, {observe:async()=>observation(x),execute:async()=>{count++;},verify:async()=>verifier(x,'UNKNOWN')});assert.equal(count,1);assert.equal(result.status,'reconciliation_required');assert.equal(result.effect_state,'unknown');await assert.rejects(new Runtime(x.store,[FIXTURE_DRAFT]).execute(x.task.id,'owner',x.lease,FIXTURE_DRAFT.route,{}, {observe:async()=>observation(x),execute:async()=>{count++;},verify:async()=>verifier(x)}));assert.equal(count,1);});
test('runtime contract response loss plus independent MATCH completes with one effect',async t=>{const x=await setup(t);let count=0;const result=await new Runtime(x.store,[FIXTURE_DRAFT]).execute(x.task.id,'owner',x.lease,FIXTURE_DRAFT.route,{}, {observe:async()=>observation(x),execute:async()=>{count++;throw Error('response lost');},verify:async()=>verifier(x)});assert.equal(count,1);assert.equal(result.status,'succeeded');assert.equal(result.effect_state,'observed');});
test('runtime contract cancellation prevents unsent work but preserves already-observed effects',async t=>{const x=await setup(t);const result=await new Runtime(x.store,[FIXTURE_DRAFT]).execute(x.task.id,'owner',x.lease,FIXTURE_DRAFT.route,{}, {observe:async()=>observation(x),execute:async()=>{x.store.cancel(x.task.id);},verify:async()=>verifier(x)});assert.equal(result.status,'cancelled');assert.equal(result.effect_state,'observed');const queued=x.store.createTask('p',FIXTURE_DRAFT.id);assert.equal(x.store.cancel(queued.id).status,'cancelled');assert.throws(()=>x.store.acquire(queued.id,'unused','unused'),/TASK_NOT_BINDABLE/);});
test('runtime contract routing depends on verified capability/environment, never model authority',()=>{const r={capability:FIXTURE_DRAFT,health:'ready',verifiedForEnvironment:true,dependency:'chrome'};const o={environment:'owned_headless',visibility:'visible'};assert.equal(chooseRoute([r],FIXTURE_DRAFT.id,o).route,FIXTURE_DRAFT.route);assert.throws(()=>chooseRoute([r],FIXTURE_DRAFT.id,{...o,visibility:'hidden'}),/NO_VERIFIED_ROUTE/);assert.throws(()=>chooseRoute([r],FIXTURE_DRAFT.id,o,['chrome']),/NO_VERIFIED_ROUTE/);assert.throws(()=>chooseRoute([{...r,verifiedForEnvironment:false}],FIXTURE_DRAFT.id,o));assert.equal(modelExecutionPermission({approved:true,confidence:1}).allowExecution,false);});
test('runtime native a waiting project does not block another project',async t=>{const x=await setup(t);x.store.begin(x.lease,FIXTURE_DRAFT.id,'write_external',{},FIXTURE_DRAFT.route);x.store.recoverTask(x.task.id);const p={...x.project,id:'p2',profileRef:'p2-profile'};x.store.registerProject(p);const task=x.store.createTask('p2',FIXTURE_DRAFT.id),lease=x.store.acquire(task.id,browserResource(p),'p2-target');x.store.begin(lease,FIXTURE_DRAFT.id,'write_external',{},FIXTURE_DRAFT.route);assert.equal(x.store.task(task.id).status,'running');assert.equal(x.store.task(x.task.id).status,'reconciliation_required');});
test('runtime native cancel before dispatch releases the resource and fences the cancelled owner',async t=>{
  const x=await setup(t);x.store.cancel(x.task.id);
  const next=x.store.createTask('p',FIXTURE_DRAFT.id),lease=x.store.acquire(next.id,browserResource(x.project),'replacement');
  assert.ok(lease.generation>x.lease.generation);
  assert.throws(()=>x.store.begin(x.lease,FIXTURE_DRAFT.id,'write_external',{},FIXTURE_DRAFT.route),/STALE_FENCE/);
  assert.equal(x.store.task(x.task.id).effect_state,'none');
});
test('runtime contract read-only verification does not invent an external write effect',async t=>{
  const x=await setup(t),capability={...FIXTURE_DRAFT,effect:'read_only'};
  const result=await new Runtime(x.store,[capability]).execute(x.task.id,'owner',x.lease,capability.route,{}, {observe:async()=>observation(x),execute:async()=>{},verify:async()=>verifier(x)});
  assert.equal(result.status,'succeeded');assert.equal(result.effect_state,'none');
});
test('runtime contract mismatched verification binding leaves the write unresolved',async t=>{
  const x=await setup(t);let effects=0;
  const result=await new Runtime(x.store,[FIXTURE_DRAFT]).execute(x.task.id,'owner',x.lease,FIXTURE_DRAFT.route,{}, {observe:async()=>observation(x),execute:async()=>{effects++;},verify:async()=>({...verifier(x),accountRef:'wrong-account'})});
  assert.equal(effects,1);assert.equal(result.status,'reconciliation_required');assert.equal(result.verification.result,'UNKNOWN');
});
