export function hermesMigrationScript(){return `
let migrationView=null,migrationCandidates=[],migrationHome='',migrationNext=null,migrationBusy=false;
const migrationErrors={MIGRATION_LEGACY_WORK_REVIEW_REQUIRED:'이전에 수동으로 가져온 같은 원본의 업무가 있습니다. 기존 업무를 확인해 주세요. 자동으로 덮어쓰거나 중복 등록하지 않습니다.',MIGRATION_SOURCE_CHANGED_RESCAN:'확인하는 동안 원본이 바뀌었습니다. 목록에서 다시 선택해 검토해 주세요.',MIGRATION_SOURCE_ALREADY_LINKED:'이미 연결된 업무가 있습니다. 기존 업무를 확인해 주세요. 새 내용으로 자동 덮어쓰지 않습니다.',MIGRATION_APPROVAL_CONFLICT:'이미 등록한 내용과 다릅니다. 기존 업무를 확인해 주세요.',MIGRATION_ALREADY_EXECUTED_USE_PAUSE:'이미 실행한 이력이 있어 가져오기를 취소할 수 없습니다. 업무 상세에서 일시정지하세요.',MIGRATION_CREDENTIAL_LIKE_INPUT:'지침에 비밀번호·토큰 같은 값이 들어 있습니다. 값은 빼고 필요한 연결 종류만 적어 주세요.',HERMES_SOURCE_DIRECTORY_REQUIRED:'Hermes 데이터 폴더를 찾지 못했습니다. 실행 환경의 경로를 확인해 주세요.',HERMES_SOURCE_NOT_FOUND:'선택한 폴더에서 Hermes 대화나 예약을 찾지 못했습니다.',MIGRATION_SOURCE_RUNTIME_UNSUPPORTED:'원본의 특수 실행 설정을 그대로 보존할 수 없습니다. 표시된 제한을 확인해 주세요.'};
document.querySelector('.import-routes').insertAdjacentHTML('beforeend','<button type="button" data-import-route="hermes" aria-pressed="false">Hermes 업무</button>');
document.getElementById('import-project').insertAdjacentHTML('afterend','<div id="import-hermes" class="import-pane" hidden><p class="muted">Hermes가 실행하고 Driver에서 관리합니다. 원본 대화·예약·인증은 그대로 둡니다.</p><label for="migration-home">Hermes 데이터 폴더 · 비워 두면 현재 프로필</label><input id="migration-home" maxlength="2048" placeholder="예: /home/me/.hermes"><div class="row"><button type="button" id="migration-discover">가져올 업무 찾기</button></div><div id="migration-sources"></div><section id="migration-review" class="import-preview" hidden></section></div>');
async function migrationPost(action,body){const response=await fetch('work/migration/'+action,{method:'POST',headers:{'content-type':'application/json','x-agent-driver':'human-office'},body:JSON.stringify(body)}),data=await response.json();if(!response.ok)throw Error(migrationErrors[data.error]||data.error||'가져오기를 완료하지 못했습니다.');return data}
async function migrationDo(callback){if(migrationBusy)return;migrationBusy=true;setMessage('가져오기 요청을 처리하는 중…');try{await callback()}catch(error){setMessage(String(error.message||error))}finally{migrationBusy=false}}
async function migrationDiscover(offset=0){await migrationDo(async()=>{const entered=document.getElementById('migration-home').value.trim(),result=await migrationPost('discover',{...(entered?{home:entered}:{}),offset});migrationCandidates=result.candidates;migrationHome=result.home;migrationNext=result.next_offset;document.getElementById('migration-home').value=result.home;const target=document.getElementById('migration-sources');target.innerHTML='<p class="muted">예약은 원본 Hermes에서 계속 유지됩니다. 새 예약을 만들지 않습니다.</p>'+migrationCandidates.map((c,i)=>'<p><button type="button" data-migration-source="'+i+'">'+esc(c.title)+' · '+(c.kind==='job'?'예약':'대화')+'</button></p>').join('')+(migrationNext!==null?'<button type="button" id="migration-more">다음 대화 보기</button>':'');target.querySelectorAll('[data-migration-source]').forEach(b=>b.onclick=()=>migrationPreviewSource(Number(b.dataset.migrationSource)));document.getElementById('migration-more')?.addEventListener('click',()=>migrationDiscover(migrationNext));setMessage('가져올 업무를 선택하세요. 아직 아무것도 실행하지 않았습니다.')})}
async function migrationPreviewSource(index){await migrationDo(async()=>{const source=migrationCandidates[index];migrationView=await migrationPost('preview',{home:migrationHome,kind:source.kind,source_id:source.source_id});renderMigration();setMessage('원본을 읽어 초안을 만들었습니다. 목표·지침·완료 조건을 확인해 주세요.')})}
async function migrationLoad(id){await migrationDo(async()=>{migrationView=await migrationPost('status',{migration_id:id});renderMigration();setMessage('이전 기록을 불러왔습니다.')})}
function renderMigration(){
 const v=migrationView,p=v.definition,s=v.source,target=document.getElementById('migration-review');target.hidden=false;
 if(v.status!=='prepared'){target.innerHTML='<h3>'+(v.status==='applied'?'가져오기 완료 · 실행 대기':'가져오기 연결 취소됨')+'</h3><p>원본 Hermes는 변경하지 않았습니다. 실행이나 예약을 시작하지 않았습니다.</p><p class="muted">기록 '+esc(v.migration_id)+' · '+(v.backup_created?'변경 전 백업 보관':'업무 등록 전')+'</p>'+(v.work_id?'<button type="button" id="migration-open-work">업무 보기</button>':'')+(v.status==='applied'?'<button type="button" id="migration-undo">첫 실행 전 연결 취소</button>':'');document.getElementById('migration-open-work')?.addEventListener('click',()=>openWork(v.work_id));document.getElementById('migration-undo')?.addEventListener('click',()=>migrationDo(async()=>{migrationView=await migrationPost('undo',{migration_id:v.migration_id});renderMigration();setMessage('연결만 취소했습니다. 원본과 이전 기록은 보존했습니다.')}));return}
 target.innerHTML='<h3>가져올 업무 확인</h3><p class="muted">이 초안은 선택한 원본의 지침을 옮긴 것입니다. 업무 해석과 과거 결과는 아직 검증되지 않았습니다. 내용이 여러 업무를 섞고 있다면 한 업무로 좁혀 주세요.</p>'+s.unknowns.map(x=>'<p class="control-note">'+esc(x)+'</p>').join('')+s.blockers.map(x=>'<p class="control-note">'+esc(x)+'</p>').join('')+(v.existing_work_id?'<p>같은 원본으로 등록된 업무가 있습니다. 중복 생성하거나 덮어쓰지 않습니다.</p><button type="button" id="migration-existing">기존 업무 보기</button>':'')+'<details><summary>원본 근거 '+s.evidence.length+'개</summary>'+s.evidence.map(e=>'<p>'+esc(e.role)+' · '+esc(e.id)+'</p><pre style="white-space:pre-wrap;overflow-wrap:anywhere">'+esc(e.text)+'</pre>').join('')+'</details><label for="migration-title">업무 이름</label><input id="migration-title" maxlength="160" value="'+esc(p.title)+'"><label for="migration-goal">목표</label><textarea id="migration-goal" maxlength="2000">'+esc(p.goal)+'</textarea><label for="migration-instruction">실행 지침</label><textarea id="migration-instruction" maxlength="4000">'+esc(p.instruction)+'</textarea><label for="migration-checks">완료 조건 · 한 줄에 하나</label><textarea id="migration-checks">'+esc(p.checks.join('\\n'))+'</textarea><label for="migration-steps">업무 단계 · 한 줄에 하나</label><textarea id="migration-steps">'+esc(p.steps.join('\\n'))+'</textarea><label><input type="checkbox" id="migration-ack">내용을 확인했습니다. Hermes 실행은 유지하고 Driver에 대기 업무로 등록합니다.</label><p class="muted">키·쿠키를 복사하지 않습니다. 가져오기 처리는 AI·Jev를 추가 호출하지 않습니다. 원본 예약을 계속 돌리고 있다면 수동 실행과 겹치지 않게 확인하세요.</p><button type="button" id="migration-apply" class="primary" '+(s.blockers.length||v.legacy_work_id?'disabled':'')+'>확인하고 가져오기</button>';
 document.getElementById('migration-existing')?.addEventListener('click',()=>openWork(v.existing_work_id));
 document.getElementById('migration-apply').onclick=()=>migrationDo(async()=>{if(!document.getElementById('migration-ack').checked){setMessage('확인 체크를 선택해 주세요. 등록해도 바로 실행하지 않습니다.');return}const lines=id=>document.getElementById(id).value.split('\\n').map(v=>v.trim()).filter(Boolean),definition={title:document.getElementById('migration-title').value.trim(),goal:document.getElementById('migration-goal').value.trim(),instruction:document.getElementById('migration-instruction').value.trim(),checks:lines('migration-checks'),steps:lines('migration-steps')};migrationView=await migrationPost('apply',{migration_id:v.migration_id,source_fingerprint:v.source_fingerprint,definition,acknowledged:true});renderMigration();setMessage(migrationView.deduplicated?'이미 등록된 같은 업무를 연결했습니다.':'업무를 등록했습니다. 실행은 다음 지시를 보낼 때 시작합니다.')});
}
document.getElementById('migration-discover').onclick=()=>migrationDiscover();
`;}
