import {type PackStore} from '../packs/store.js';
import {type HostConfig} from '../interface/config.js';
import {type ControlCenterSnapshot} from './control-center.js';
import {safeControlText} from './control-center.js';
import {type SwarmPlan,type SwarmRunSnapshot} from '../swarm/contracts.js';

const stageNames:Record<string,string>={discovery:'탐색',source_read:'자료 확인',verification:'검증',reduction:'정리',synthesis:'결과 작성'};
function downstream(snapshot:SwarmRunSnapshot,id:string){const affected=new Set([id]);let changed=true;while(changed){changed=false;for(const item of snapshot.plan.workers)if(!affected.has(item.id)&&item.depends_on.some(dep=>affected.has(dep))){affected.add(item.id);changed=true;}}affected.delete(id);return [...affected];}
export function readOffice(store:PackStore,config:HostConfig,control:ControlCenterSnapshot){
  const project=config.project.id;
  const runDetails=control.runs.map(run=>{
    if(run.kind!=='swarm')return {id:`${run.kind}:${run.id}`,run_id:run.id,kind:run.kind,title:run.title,status:run.status,paused:false,revision:0,run_revision:null,verified_steps:0,total_steps:0,progress_percent:null,progress_basis:'이 실행 경로는 단계별 독립 검증 결과를 보고하지 않음',stages:run.actors.map(actor=>({id:actor.id,stage:actor.stage,label:actor.label,objective:safeControlText(actor.detail,500),status:actor.status,verified:false,attempts:0,executor:actor.executor,owner:null,latest_activity:actor.activity,instruction_version:0,can_edit:false,effect:'unobserved',role:null,depends_on:[],downstream:[],source_urls:[],completion_evidence:[],result:null,quality:null})),can_pause:false,can_edit:false,attention_reason:run.lane==='attention'?run.actors.find(actor=>actor.activity)?.activity??run.status:null,updated_at:run.updated_at,events:control.activities.filter(event=>event.run_id===run.id&&event.run_kind===run.kind).slice(-100).map(event=>({id:event.id,kind:event.kind,worker_id:event.actor_id,detail:safeControlText(event.summary,300),created_at:event.created_at})),brief:null,plan:null,outcome:null,method:null};
    const snapshot=store.swarmRun(project,run.id).snapshot as SwarmRunSnapshot,office=store.officeControl(project,run.id),activities=store.swarmActivities(project,0,500,run.id),instructions=store.officeInstructions(project,run.id);
    const steps=snapshot.plan.workers.map(def=>{const worker=snapshot.workers[def.id]!,latestInstruction=instructions.filter(item=>item.worker_id===def.id).at(-1),activity=activities.filter(item=>item.worker_id===def.id).at(-1),reported=activities.filter(item=>item.worker_id===def.id&&item.kind==='worker.activity'&&item.body&&typeof item.body==='object'&&'actor_id' in item.body&&typeof item.body.actor_id==='string').at(-1),actorId=reported?.body&&typeof reported.body==='object'&&'actor_id' in reported.body?String(reported.body.actor_id):null;
      const verified=worker.status==='succeeded'&&worker.result?.readback?.verified===true&&worker.quality?.accepted===true;
      const dependent=downstream(snapshot,def.id);
      return {id:def.id,stage:def.stage,label:stageNames[def.stage]??def.stage,objective:safeControlText(def.objective,500),status:worker.status,verified,attempts:worker.attempts,executor:def.executor,owner:worker.status==='leased'?`${actorId??'에이전트 ID 미보고'} · ${def.executor} · 시도 ${worker.attempts}`:null,latest_activity:activity?.kind??null,instruction_version:latestInstruction?.version??0,can_edit:worker.status==='pending'&&def.effect==='read_only'&&dependent.every(id=>snapshot.workers[id]?.status==='pending'),effect:def.effect,role:safeControlText(def.role,160),depends_on:def.depends_on,downstream:dependent,source_urls:def.source_urls.slice(0,8).map(url=>safeControlText(url,220)),completion_evidence:def.completion_evidence.map(item=>safeControlText(item,400)),result:worker.result?{status:worker.result.status,summary:safeControlText(worker.result.summary,1000),readback:worker.result.readback?{verified:worker.result.readback.verified,method:worker.result.readback.method,observed_at:worker.result.readback.observed_at}:null,evidence:worker.result.evidence.slice(0,12).map(item=>({source_url:safeControlText(item.source_url,220),claim:safeControlText(item.claim,500),verification:item.verification})),artifacts:worker.result.artifacts.slice(0,12).map(item=>({kind:item.kind,summary:safeControlText(item.summary,500),sha256:item.sha256}))}:null,quality:worker.quality?{accepted:worker.quality.accepted,score:worker.quality.score}:null};
    });
    const verified=steps.filter(step=>step.verified).length,review=snapshot.reviews.at(-1),pauseEvent=office.paused?store.officeEvents(project,run.id).filter(event=>event.kind==='user.pause').at(-1):null,blocked=office.paused?(pauseEvent?.detail.includes('awaiting reconciliation: none')?'사용자가 일시정지함':'사용자가 일시정지함 · 진행 중인 외부 변경은 결과 확인 전까지 재개할 수 없음'):review?.reason??(run.status==='running'&&steps.some(step=>step.status==='pending'&&run.actors.find(actor=>actor.id===step.id)?.status==='waiting_for_auth')?'사이트 로그인이 필요함':null);
    const work=store.officeWork(project,'swarm',run.id) as {id:string;goal:string}|null;
    const plan=snapshot.plan;
    const original=store.swarmPlan(project,plan.plan_id).plan as SwarmPlan;
    return {id:work?.id??`swarm:${run.id}`,run_id:run.id,kind:run.kind,title:run.title,status:snapshot.status,paused:office.paused,revision:office.revision,run_revision:snapshot.revision,verified_steps:verified,total_steps:steps.length,progress_percent:steps.length?Math.floor(100*verified/steps.length):null,progress_basis:'독립 확인과 품질 검사를 통과한 단계만 완료로 계산',stages:steps,can_pause:['running','needs_human'].includes(snapshot.status),can_edit:steps.some(step=>step.can_edit),attention_reason:blocked,updated_at:snapshot.updated_at,brief:{request:safeControlText(original.goal,3000),current_goal:safeControlText(plan.goal,3000),completion_rule:'모든 단계의 독립 결과 확인과 품질 승인',worker_count:steps.length,created_at:plan.created_at},plan:{id:plan.plan_id,summary:safeControlText(plan.summary,2000),planner_model:safeControlText(plan.planner.model,128),max_concurrency:plan.max_concurrency,mode:plan.research_mode},outcome:{verified:steps.length>0&&verified===steps.length&&snapshot.status==='completed',summary:steps.filter(step=>step.stage==='synthesis'&&step.result).map(step=>step.result!.summary).join('\n')||null,review_count:snapshot.reviews.length,last_review:snapshot.reviews.at(-1)?.reason??null},method:{status:'candidate',basis:'저장된 실행 계획을 바탕으로 한 반복 방법 초안이며 Task Pack 승격은 별도 검증이 필요함'},events:[...store.officeEvents(project,run.id).map(event=>({id:`office:${event.id}`,kind:event.kind,worker_id:event.worker_id,detail:safeControlText(event.detail,500),created_at:event.created_at})),...activities.slice(-80).map(event=>({id:`swarm:${event.id}`,kind:event.kind,worker_id:event.worker_id,detail:safeControlText((event.body&&typeof event.body==='object'&&'summary' in event.body?String(event.body.summary):event.kind),300),created_at:event.created_at}))].sort((a,b)=>a.created_at.localeCompare(b.created_at)).slice(-100)};
  });
  const grouped=new Map<string,typeof runDetails[number]>(),runsByWork=new Map<string,Array<{run_id:string;status:string;updated_at:string|null;verified_steps:number;total_steps:number}>>();
  for(const item of runDetails){const runs=runsByWork.get(item.id)??[];runs.push({run_id:item.run_id,status:item.status,updated_at:item.updated_at,verified_steps:item.verified_steps,total_steps:item.total_steps});runsByWork.set(item.id,runs);if(!grouped.has(item.id))grouped.set(item.id,item);}
  const works=[...grouped.values()].map(item=>({...item,runs:runsByWork.get(item.id)??[]}));
  return {format:2,project_id:project,generated_at:new Date().toISOString(),works,run_details:runDetails,health:control.health,website_connections:control.website_connections,coverage:control.coverage,latest_revision:control.latest_revision+':'+runDetails.map(work=>`${work.run_id}:${work.revision}`).join(',')};
}
