const roles=[['planner','계획'],['worker','실행'],['verifier','검증'],['synthesis','종합']] as const;
const clients=[['codex','Codex'],['claude','Claude Code'],['opencode','OpenCode']] as const;
export const roleModelSettingsHtml=`<div id="role-model-policy"><label for="role-model-mode">역할별 모델</label><select id="role-model-mode"><option value="inherit">기본 모델 사용</option><option value="manual">역할별 직접 지정</option><option value="auto">Auto · 태스크별 자동 배분</option></select><p id="role-model-mode-help" class="muted keep"></p><details id="role-model-settings" class="settings-help" hidden><summary>역할별 모델 지정</summary><p class="keep">비워 둔 역할은 앱별 기본 모델을 사용합니다.</p><p class="keep">MCP 클라이언트가 직접 판단하는 경우 모델은 해당 앱이 선택합니다.</p>${roles.map(([role,label])=>`<fieldset class="role-model-row"><legend>${label}</legend><div class="row">${clients.map(([client,name])=>`<div><label for="role-${role}-${client}">${name}</label><select id="role-${role}-${client}"><option value="">선택한 모델 상속</option></select></div>`).join('')}</div></fieldset>`).join('')}</details><details class="settings-help"><summary>적용 범위</summary><p class="keep">구독 앱을 쓸 때만 적용합니다. 코딩 전용 설정과 API 사용 시에는 적용하지 않습니다.</p><p class="keep">Auto는 실행 전에 LLM을 한 번 호출해 배분하고, 업무와 설정이 같으면 재사용합니다. 후보를 확인할 수 없으면 기본 모델로 진행합니다.</p><p class="keep">구독 인증이 확인된 앱만 자동 배분 후보가 됩니다. OpenCode의 인증 종류가 확인되지 않으면 자동 후보에서 제외합니다.</p></details></div>`;
export const roleModelSettingsScript=`
const modelRoles=['planner','worker','verifier','synthesis'];
function rolePolicyFields(){const mode=$('role-model-mode').value;$('role-model-settings').hidden=mode!=='manual';$('role-model-mode-help').textContent=mode==='auto'?'LLM이 태스크에 맞게 배분합니다. 결과와 이유는 업무 상세에서 확인하세요.':mode==='manual'?'계획·실행·검증·종합 역할에만 기본 모델 대신 적용합니다.':'모든 역할에서 위의 앱별 기본 모델을 사용합니다.';}
function fillRoleModels(reset=false){if(reset)$('role-model-mode').value=state.selection.role_model_mode||(state.selection.role_models?'manual':'inherit');for(const role of modelRoles)for(const client of ['codex','claude','opencode']){const id='role-'+role+'-'+client;fillModels(id,clientCatalogs[client]?.models||[],reset?state.selection.role_models?.[role]?.[client]:$(id).value,'선택한 모델 상속');}rolePolicyFields();}
function roleModelValues(){if(modelScope!=='global')return state.selection.role_models;const roles=Object.fromEntries(modelRoles.map(role=>[role,Object.fromEntries(['codex','claude','opencode'].map(client=>[client,$('role-'+role+'-'+client).value||null]))]));return state.selection.role_models||Object.values(roles).some(row=>Object.values(row).some(Boolean))?roles:undefined;}
$('role-model-mode').onchange=rolePolicyFields;
// Explain the hierarchy next to the actual selectors, not in a remote tooltip.
document.querySelector('label[for="client"]').textContent='기본 클라이언트';
$('client').insertAdjacentHTML('afterend','<p class="muted keep" id="default-client-help">업무를 처음 분석할 앱입니다. 연결이 안 되면 다른 연결된 앱으로 넘깁니다.</p>');
$('codex-model').closest('.row').insertAdjacentHTML('beforebegin','<h3 id="default-model-heading">앱별 기본 모델</h3><p class="muted keep" id="default-model-help">각 앱 안에서 사용할 모델입니다. Auto를 켜면 실행 역할별로 바뀔 수 있습니다.</p>');
`;
