import {displayOptionsHtml,sidebarHtml,themeScript,uiCss} from './ui-shell.js';
import {i18nScript} from './i18n.js';
import {browserSetupHtml,browserSetupScript} from './browser-setup-ui.js';
export function settingsHtml(nonce:string){return `<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>연결 및 설정 · Agent Office</title>
<style>${uiCss}
.flow{display:grid;grid-template-columns:1fr 28px 1fr 28px 1fr;align-items:stretch;margin:0 0 18px}.flow i{height:1px;background:var(--line2);align-self:center}.nd{border:1px solid var(--line2);border-radius:var(--r);padding:10px 14px;background:var(--panel);min-width:0;text-align:center;display:grid;align-content:center}.nd b{display:block;font:500 14px var(--mono)}.nd small{font:11.5px var(--mono);color:var(--dim)}.nd.hot{border-color:var(--accent);box-shadow:0 0 0 3px var(--acc-a)}
@media(max-width:700px){.flow{grid-template-columns:1fr}.flow i{width:1px;height:12px;margin:auto}}
.steps4{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:4px;border-bottom:1px solid var(--line);margin:4px 0 14px}.steps4 button{border:0;border-bottom:2px solid transparent;border-radius:0;background:none;color:var(--dim);padding:8px 6px;display:flex;align-items:center;justify-content:center;gap:6px;white-space:normal}
.steps4 button.active{color:var(--text);border-bottom-color:var(--accent);font-weight:600}.si{width:16px;height:16px;border-radius:50%;border:1px solid var(--line2);font-size:10px;line-height:14px;text-align:center;color:var(--faint)}.si.done{background:var(--ok);border-color:var(--ok);color:var(--bg)}
.settings{max-width:760px}.panel h2{font-size:16px;margin-bottom:4px}.panel>p.muted{margin:0 0 10px}
.runtime-line{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));align-items:center;justify-items:center;text-align:center;gap:12px;padding:12px 0;border-bottom:1px solid var(--line)}.runtime-line .badge{white-space:normal}
.list,.browser-list{display:grid;grid-template-columns:minmax(0,1fr) max-content max-content;column-gap:16px}.client{min-width:0;padding:14px 0;border-bottom:1px solid var(--line);display:grid;grid-column:1/-1;grid-template-columns:subgrid;align-items:center;row-gap:12px}.crow{display:grid;grid-column:1/-1;grid-template-columns:subgrid;align-items:center;column-gap:16px;row-gap:12px}
.client strong{display:grid;grid-column:1/span 2;grid-template-columns:subgrid;align-items:center;font-weight:500}.client>.hint{grid-column:1/-1;justify-self:end;margin:0}.client .sep{display:none}.client .cname{min-width:0;overflow-wrap:anywhere;justify-self:stretch;text-align:left;display:flex;gap:10px;align-items:center;font-weight:600}.client-icon{display:inline-flex;align-items:center;justify-content:center;width:36px;height:36px;flex:0 0 36px;border:1px solid var(--line);border-radius:8px;background:var(--bg);color:var(--text)}.client-icon svg{width:24px;height:24px}.client-icon[data-client=claude]{color:#d97757}.client-icon[data-client=hermes]{color:var(--accent)}.client .badge{white-space:normal;justify-self:center;align-self:center}.cact{grid-column:3;min-width:0;max-width:100%;display:flex;flex-wrap:wrap;gap:8px;align-items:center;justify-content:flex-end;justify-self:end;min-height:36px}.cact button,.cact .action-link{width:auto;min-width:0;min-height:36px;text-align:center;font-size:12.5px;white-space:normal;line-height:1.4}.cact a{font-size:12px}.cact button[data-setup-complete]{opacity:1;color:var(--ok);border-color:var(--ok);background:var(--ok-a);cursor:default}.client>.browser-help{grid-column:1/-1;margin-top:0}.browser-help a{display:block;margin-top:8px;color:var(--code);text-decoration:underline;text-underline-offset:3px}.cact .login-action{border-color:var(--accent);color:var(--accent);background:var(--acc-a)}
.client p{grid-column:1/-1;margin:0;font-size:12px}.client p.muted.hinted{display:none}.client>.device{grid-column:1/-1}.client>.cact{justify-content:flex-end}.client .login-hint{display:block;font-size:12px;margin-top:12px;color:var(--dim)}
.device{margin-top:8px;padding:8px 10px;background:var(--raise);border-radius:6px;overflow-wrap:anywhere;font-size:13px}.device code{display:block;font-size:20px;margin-top:6px;letter-spacing:.08em}
.row{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,200px),1fr));gap:12px;align-items:start}.row>*{min-width:0}.row label{text-align:center}.actions{display:flex;flex-wrap:wrap;gap:8px;justify-content:flex-end;align-items:stretch;margin-top:16px}.actions button{width:auto;white-space:normal;line-height:1.4}
details{margin-top:12px;color:var(--dim)}details summary{cursor:pointer}details label{color:var(--text)}#windows-bridge-config{white-space:pre-wrap;overflow-wrap:anywhere}
.settings-help{margin:8px 0 12px}.settings-help p{margin:8px 0;font-size:13px;line-height:1.6}.settings-help>summary{width:max-content;max-width:100%}.browser-guide{margin-top:16px;padding-top:12px;border-top:1px solid var(--line)}.browser-guide h4{margin:0 0 8px;color:var(--text);font-size:13px}.browser-guide a{display:block;width:fit-content;margin-top:8px;color:var(--code);text-decoration:underline;text-underline-offset:3px}.browser-feedback[hidden],#browser-setup-notice[hidden]{display:none}
.consent{margin-top:14px;padding:10px 12px;border:1px solid var(--line);border-radius:6px}.consent label{margin:0;color:var(--text)}
.terminal{margin:14px 0 0;border:1px solid var(--line);border-radius:var(--r);background:var(--panel)}.terminal-head{display:grid;grid-template-columns:140px minmax(0,1fr) 100px;align-items:center;gap:12px;padding:8px 12px;font-size:12px;cursor:pointer;list-style:none;text-align:center}.terminal-head::-webkit-details-marker{display:none}
#tail-last{flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.terminal pre{margin:0;padding:10px 12px;max-height:220px;overflow:auto;white-space:pre-wrap;overflow-wrap:anywhere;border-top:1px solid var(--line);color:var(--dim)}
#clients,#mcp-clients{grid-auto-rows:1fr;row-gap:8px;margin:12px 0}#clients .client,#mcp-clients .client{border:1px solid var(--line);border-radius:8px;padding:12px;align-content:center}#clients .device{text-align:left}.connection-title{margin-top:16px}#refresh-clients,#refresh-api-models,#browser-setup-refresh{margin-top:0}.field-action{display:flex;justify-content:flex-end;margin:12px 0}.field-action>button{width:auto;min-width:0;white-space:normal;line-height:1.4}.browser-list{grid-template-columns:minmax(0,1fr) minmax(0,1fr) minmax(0,2fr)}.browser-list strong{grid-column:auto;display:block;justify-self:center;text-align:center;min-width:0;overflow-wrap:anywhere}.settings>button{display:block;margin:12px 0 0 auto}#windows-bridge>button{display:block;margin:12px 0 0 auto}
@media(max-width:620px){.list{grid-template-columns:minmax(0,1fr) minmax(0,max-content)}.browser-list{grid-template-columns:repeat(2,minmax(0,1fr))}.cact{grid-column:2;justify-self:end}.browser-list .cact{grid-column:1/-1}.client-icon{width:28px;height:28px;flex-basis:28px}.client-icon svg{width:20px;height:20px}.client .cname{gap:8px}.terminal-head{grid-template-columns:minmax(0,1fr) 100px}.terminal-head #tail-last{grid-column:1/-1;grid-row:2}.terminal-head #tail-state{grid-column:2;grid-row:1}}@media(max-width:380px){.runtime-line{grid-template-columns:1fr}.steps4 .si{display:none}}</style>
<div class="app">${sidebarHtml('settings')}<main class="main"><div class="settings"><header class="top"><h1>연결 및 설정</h1><span class="muted mono" id="progress">설정을 불러오는 중…</span>${displayOptionsHtml}</header><div class="flow" aria-hidden="true"><div class="nd"><b>mcp client</b><small>claude code · codex · cursor · hermes</small></div><i></i><div class="nd hot"><b>agent-office mcp</b><small>stdio · observe · pack plan</small></div><i></i><div class="nd"><b>LOCAL</b><small>no cloud relay</small></div></div><nav class="steps4" aria-label="설정 단계"><button data-step="0"><span class="si" id="si-0" aria-hidden="true">1</span>에이전트</button><button data-step="1"><span class="si" id="si-1" aria-hidden="true">2</span>로컬 실행</button><button data-step="2"><span class="si" id="si-2" aria-hidden="true">3</span>AI</button><button data-step="3"><span class="si" id="si-3" aria-hidden="true">4</span>Jev</button></nav>
<section class="panel" id="step-0" hidden><h2>에이전트 연결</h2><p class="muted">업무를 맡길 앱을 연결하세요. 앱이 없으면 여기에서 설치와 로그인, MCP 등록을 진행할 수 있습니다.</p><div class="runtime-line"><strong>Agent Office 런타임</strong><span class="badge idle" id="driver-state">설치 확인 중</span></div><div id="mcp-clients" class="list"></div><details id="windows-bridge" hidden><summary>Windows AI 앱 연결 · 선택</summary><p class="muted keep" id="windows-bridge-help">Cursor 같은 Windows AI 앱의 채팅에서 Agent Office에 업무를 맡기고 싶을 때만 설정하세요. 위에서 WSL 앱을 연결했다면 건너뛰어도 됩니다.</p><p class="muted keep">예: Windows AI 앱에서 요청 → WSL의 Agent Office가 도구 실행 → 같은 채팅에서 결과 확인.</p><ol class="muted keep"><li>사용할 Windows AI 앱의 설정에서 MCP 서버 추가를 여세요.</li><li>이름은 agent-office로 지정하세요. JSON 입력란에는 아래 설정을, 명령·인수가 나뉜 입력란에는 command와 args 값을 각각 넣으세요.</li><li>저장한 뒤 해당 앱의 MCP 목록에서 연결 상태와 도구 목록을 확인하세요. 이 관제센터에서는 Windows 앱의 등록 여부를 확인할 수 없습니다.</li></ol><p class="muted keep">아래 내용은 앱의 연결 설정입니다. PowerShell·WSL 터미널이나 채팅에 실행하는 명령이 아닙니다. 모든 Windows 앱에 공통으로 붙여넣는 기능도 아닙니다.</p><pre class="device" id="windows-bridge-config" data-i18n-skip></pre><button id="copy-windows-bridge">설정 복사</button></details><div class="actions"><button id="refresh-mcp">다시 확인</button><button id="mcp-next" data-next="1" class="primary">다음</button></div></section>
<section class="panel" id="step-1" hidden><h2>로컬 실행</h2><p class="muted">기본 전용 브라우저는 내 화면을 빼앗지 않습니다. 별도 브라우저 연결은 아래에서 선택할 수 있습니다.</p><div class="runtime-line"><strong>전용 작업 환경</strong><span class="badge idle" id="computer-state"></span></div>${browserSetupHtml}<div class="actions"><button id="connect-computer" class="primary">로컬 실행 승인</button><button data-next="2">다음</button></div></section>
<section class="panel" id="step-2" hidden><h2>AI 연결</h2><p class="muted">사용 중인 구독이나 API 키를 선택하세요. 선택한 앱을 먼저 사용하고, 인계 시 받는 앱에 저장한 모델을 적용합니다.</p><p class="muted keep">구독 한도를 소진해도 유료 API로 자동 전환하지 않습니다.</p><label for="mode">연결 방식</label><select id="mode"><option value="subscription">구독 사용</option><option value="api">API 키 사용</option></select><div id="subscription-fields"><label for="client">우선 사용할 클라이언트</label><select id="client"><option value="auto">자동 선택</option><option value="mcp">연결된 MCP 클라이언트</option><option value="codex">Codex</option><option value="claude">Claude Code</option><option value="opencode">OpenCode</option></select><div class="field-action"><button id="refresh-clients">연결 상태 확인</button></div><div id="clients" class="list"></div></div><div class="row"><div><label for="codex-model">Codex 모델</label><select id="codex-model"><option value="">클라이언트 기본값</option></select></div><div><label for="claude-model">Claude Code 모델</label><select id="claude-model"><option value="">클라이언트 기본값</option></select></div><div><label for="opencode-model">OpenCode 모델</label><select id="opencode-model"><option value="">클라이언트 기본값</option></select></div></div><p class="muted keep" id="catalog-state">모델 목록은 연결된 앱에서 확인합니다. 기본값은 앱 업데이트를 따릅니다.</p>
<div id="api-fields" hidden><div class="row"><div><label for="api-provider">공급자</label><select id="api-provider"><option value="openai">OpenAI</option><option value="anthropic">Anthropic</option><option value="openrouter">OpenRouter</option><option value="openai_compatible">OpenAI 호환 서버</option></select></div><div><label for="reasoning">추론 강도</label><select id="reasoning"><option>low</option><option>medium</option><option>high</option></select></div></div><div id="base-url-fields" hidden><label for="api-base-url">API 주소</label><input id="api-base-url" type="url" placeholder="https://provider.example/v1"></div><label for="api-model">모델</label><select id="api-model"></select><div class="field-action"><button id="refresh-api-models" aria-label="현재 모델 목록 새로고침">모델 새로고침</button></div><label for="api-model-custom">목록에 없는 모델 ID</label><input id="api-model-custom" maxlength="200" placeholder="직접 입력 시 목록 선택보다 우선"><label for="api-key">API 키</label><input id="api-key" type="password" autocomplete="new-password" placeholder="키 입력"><p class="muted" id="api-state"></p><label><input id="api-consent" type="checkbox"> API 사용 요금을 확인했습니다.</label><label><input id="api-to-subscription" type="checkbox"> API 인증·한도 오류 시 연결된 구독 앱으로 이어가기</label><details><summary>저장된 키 관리</summary><label><input type="checkbox" id="remove-api"> 저장된 API 키 삭제</label></details></div><div class="consent" id="work-data-row" hidden><label><input id="work-data" type="checkbox"> 업무 내용을 선택한 AI로 보내 정의·계획하도록 허용</label><p class="muted">한 줄 업무와 가져온 자료의 요약을 선택한 구독 앱이나 API 모델로 보냅니다. 끄면 업무는 저장되지만 AI 정의 단계에서 멈춥니다. 로컬 runtime-config.json의 work.model_data_approved에 기록됩니다.</p></div><div class="actions"><button id="save-model">저장</button><button data-save-next="3" class="primary">다음</button></div></section>
<section class="panel" id="step-3" hidden><h2>Jev 연결</h2><p class="muted">빠른 반복 판단에 사용합니다. 연결하지 않아도 LLM으로 진행합니다.</p><label for="jev-mode">사용 방식</label><select id="jev-mode"><option value="inherit">자동</option><option value="off">사용하지 않음</option><option value="on">API 키로 연결</option></select><div id="jev-fields" hidden><label for="jev-key">TypeSafe / Jev API 키</label><input id="jev-key" type="password" autocomplete="new-password" placeholder="키 입력"><p id="jev-state" class="muted"></p><details><summary>저장된 키 관리</summary><label><input type="checkbox" id="remove-jev"> 저장된 Jev 키 삭제</label></details></div><div class="actions"><button id="save-jev">저장</button><button id="finish" class="primary">완료</button></div></section>
<p class="notice" role="status" aria-live="polite" id="notice"></p><details class="terminal" aria-label="연결 작업 기록"><summary class="terminal-head"><span>연결 작업 기록</span><span id="tail-last"></span><span id="tail-state">연결 중</span></summary><p class="muted" style="margin:12px 14px 0;font-size:13px">이 화면에서 실행한 설치·연결의 시작과 결과입니다. 터미널 원문은 저장하지 않습니다. 실제 업무 기록은 <a href="./">업무 현황</a>의 업무 상세에서 확인하세요.</p><pre id="setup-log" aria-live="polite">아직 연결 작업 기록이 없습니다.</pre></details></div></main></div>
<script nonce="${nonce}">
${i18nScript}
${themeScript}
function compactHints(root){for(const scope of root.querySelectorAll('.panel,#coding-scope-options,.consent')){const notes=[...scope.querySelectorAll('p.muted:not([id])')].filter(node=>!node.closest('details,.client')&&node.closest('.panel,#coding-scope-options,.consent')===scope);if(!notes.length)continue;let help=scope.querySelector('details.settings-help');if(!help){help=document.createElement('details');help.className='settings-help';const summary=document.createElement('summary');summary.textContent='설명 보기';help.append(summary);const heading=scope.querySelector('h2');if(heading)heading.after(help);else scope.append(help);}for(const note of notes)help.append(note);}}
const $=id=>document.getElementById(id);let state,mcpState,bootstrapState,step=0,busy=false,initialized=false,flowTimer,clientsLoaded=false,mcpLoaded=false,clientCatalogs={},apiCatalog=null,apiCatalogProvider=null,modelScope='global';
document.querySelector('label[for="mode"]').insertAdjacentHTML('beforebegin','<label for="model-scope">설정 대상</label><select id="model-scope"><option value="global">전역 · 기본 AI</option><option value="coding">코딩 업무 전용</option></select><div id="coding-scope-options" hidden><label><input type="checkbox" id="coding-inherit"> 전역 AI 설정 사용</label><p class="muted keep">해제하면 코딩 계획·조언과 아래 CLI 모델은 이 설정을 우선합니다. 이미 연결한 코딩 세션과 실행 중인 호출은 기존 모델을 유지합니다.</p><p class="muted keep">실제 코드 작업은 Codex·Claude CLI가 수행합니다. API 선택은 계획·조언용이며, 같은 공급자·주소이면 전역 API 키를 재사용합니다.</p></div>');
function scopeFields(locked=busy){$('model-scope').value=modelScope;$('coding-scope-options').hidden=modelScope!=='coding';$('work-data-row').hidden=modelScope==='coding'||!state?.work_model_data?.editable;const inherited=modelScope==='coding'&&$('coding-inherit').checked;document.querySelectorAll('#step-2 input,#step-2 select,#step-2 button').forEach(node=>{if(!['model-scope','coding-inherit','save-model'].includes(node.id)&&!node.hasAttribute('data-save-next'))node.disabled=locked||inherited;});}
async function selectModelScope(scope){const next=await request(scope==='coding'?'settings/coding/status':'settings/status');modelScope=scope;state=next;apiCatalog=null;apiCatalogProvider=null;for(const name of ['api','jev']){$(name+'-key').value='';$('remove-'+name).checked=false;}$('coding-inherit').checked=Boolean(next.inherit_global);populate();notice(scope==='coding'?'코딩 전용 설정입니다. 전역 설정은 바뀌지 않습니다.':'전역 AI 설정입니다.');}
function fillModels(id,models,selected,defaultLabel='클라이언트 기본값'){const field=$(id);field.replaceChildren();const first=document.createElement('option');first.value='';first.textContent=defaultLabel;field.append(first);for(const row of models){const item=document.createElement('option');item.value=row.id;item.textContent=row.label===row.id?row.id:row.label+' · '+row.id;field.append(item);}if(selected&&!models.some(row=>row.id===selected)){const item=document.createElement('option');item.value=selected;item.textContent=selected+' · 저장된 모델';field.append(item);}field.value=selected||'';}
const notice=text=>$('notice').textContent=text;
const authWindows=new Map();
function reserveAuthWindow(id){if(!['codex','opencode','cursor'].includes(id)||busy||!initialized)return;const prior=authWindows.get(id);if(prior&&!prior.closed){prior.focus();return;}const tab=window.open('about:blank','_blank');if(tab){tab.opener=null;tab.document.title='Agent Office · Login';tab.document.body.textContent=window.officeLang==='ko'?'공식 로그인 화면을 준비하고 있습니다. 이 창은 자동으로 이동합니다.':'Preparing the official login page. This window will continue automatically.';authWindows.set(id,tab);}}
function closeAuthWindow(id){const tab=authWindows.get(id);try{if(tab&&!tab.closed&&tab.location.href==='about:blank')tab.close();}catch{}authWindows.delete(id);}
function pollAuth(){clearInterval(flowTimer);flowTimer=setInterval(pollFlows,1200);}
function loginAction(id,kind){reserveAuthWindow(id);return action(async()=>{try{const started=await request('settings/login',{client:id,flow:kind});renderFlow(started);pollAuth();}catch(error){closeAuthWindow(id);throw error;}});}
function installAction(id){reserveAuthWindow(id);return action(async()=>{try{notice('설치 중… 연결 작업 기록에서 진행 상황을 확인하세요.');const result=await request('settings/client/install',{client:id});await refreshMcp();if(step===2)await refreshClients();if(result.login){renderFlow(result.login);pollAuth();}}catch(error){closeAuthWindow(id);throw error;}});}
function clientRow(name,stateLabel,tone,id){const row=document.createElement('div');row.className='crow';const title=document.createElement('strong'),n=document.createElement('span'),icon=document.createElement('span'),label=document.createElement('span'),sep=document.createElement('span'),badge=document.createElement('span'),actions=document.createElement('div');n.className='cname';icon.className='client-icon';icon.dataset.client=id;icon.setAttribute('aria-hidden','true');const paths={codex:'<rect x="3" y="4" width="18" height="16" rx="4"/><path d="m7 9 3 3-3 3m6 0h4"/>',claude:'<path d="M12 3v18M3 12h18M5.6 5.6l12.8 12.8M5.6 18.4 18.4 5.6M8.6 3.7l6.8 16.6M3.7 8.6l16.6 6.8M3.7 15.4l16.6-6.8M8.6 20.3l6.8-16.6"/>',opencode:'<path d="m8 7-5 5 5 5m8-10 5 5-5 5m-3-12-2 14"/>',cursor:'<path d="m12 3 9 5v8l-9 5-9-5V8l9-5Zm0 0v18M3 8l9 5 9-5"/>',hermes:'<path d="M4 20c2-10 5-15 16-16-1 9-6 14-14 14m-2 2L16 8M8 13h6"/>'};icon.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">'+(paths[id]||paths.codex)+'</svg>';label.textContent=name;n.append(icon,label);sep.className='sep';sep.textContent=' · ';badge.className='badge '+tone;badge.textContent=stateLabel;title.append(n,sep,badge);actions.className='cact';row.append(title,actions);return row}
function addClientManage(actions,id,name,fromAgents=false){const button=document.createElement('button');button.textContent='관리';button.dataset.manageClient=id;button.setAttribute('aria-label',name+' 관리');button.onclick=async()=>{let target;await action(async()=>{await show(fromAgents||$(id+'-model')?2:0);const field=$(id+'-model');target=field&&!field.closest('[hidden]')?field:step===2?$('client-'+id):document.querySelector('#mcp-clients [data-client="'+id+'"]');if(target?.closest('[hidden]'))target=$('mode');});if(target?.isConnected){if(!['SELECT','BUTTON','INPUT'].includes(target.tagName))target.tabIndex=-1;target.scrollIntoView({block:'center',behavior:'auto'});target.focus({preventScroll:true});}};actions.append(button);}
function stepMarks(){const done=[Boolean(mcpState?.registered_count),Boolean(state?.computer?.connected),Boolean(state?.configured&&state.onboarding_step>=3),Boolean(state?.configured&&state.onboarding_step>=4)];done.forEach((ok,i)=>{const m=$('si-'+i);if(m){m.classList.toggle('done',ok);m.textContent=ok?'✓':String(i+1)}})}
const labels={ready:'연결됨',signed_out:'로그인 필요',expired:'다시 로그인 필요',unavailable:'사용할 수 없음',unknown:'확인되지 않음',unchecked:'미확인',needs_login:'로그인 필요',challenge:'사용자 확인 필요',retry_requested:'재확인 요청됨',policy_blocked:'미확인'};
async function request(path,body,site=false){if(modelScope==='coding'&&body!==undefined&&['settings/save','settings/provider-probe','settings/models'].includes(path))path=path.replace('settings/','settings/coding/');const checking=['settings/mcp/check','settings/refresh','settings/browsers/check'].includes(path);if(checking)$('tail-last').textContent=window.officeText('연결 상태 확인 중…');let response;try{response=await fetch(path,{cache:'no-store',...(body===undefined?{}:{method:'POST',headers:{'content-type':'application/json','X-Agent-Driver':site?'human-connection':'human-settings'},body:JSON.stringify(body)})});}catch(error){if(checking)appendActivity({at:new Date().toISOString(),area:'setup',state:'error',message:'관제센터에 연결하지 못했습니다. 네트워크를 확인한 뒤 다시 누르세요.'});throw error;}const data=await response.json();if(!response.ok)throw Error(data.error||'연결 오류');return data;}
function lockControls(locked){document.querySelectorAll('.steps4 button,.panel button,.panel input,.panel select,#copy-windows-bridge').forEach(node=>node.disabled=locked);if(!locked){$('connect-computer').disabled=state?.computer.connected??true;$('mcp-next').disabled=!(mcpState?.registered_count||mcpState?.windows_bridge);}scopeFields(locked);document.querySelectorAll('[data-setup-complete]').forEach(node=>node.disabled=true);}
async function action(fn){if(!initialized||busy)return;busy=true;lockControls(true);try{await fn();}catch(error){notice(({MODEL_SETTINGS_CONFLICT:'다른 창에서 설정이 바뀌었습니다. 새로고침 후 다시 저장하세요.',MODEL_PROVIDER_CREDENTIAL_REQUIRED:'선택한 공급자의 API 키를 입력하거나 구독 방식으로 전환하세요.',MODEL_PROVIDER_PROBE_REQUIRED:'API 연결 확인이 만료되었거나 설정이 바뀌었습니다. 다시 확인해 주세요.',MODEL_PROVIDER_UNAVAILABLE:'공급자 연결·키·모델을 확인해 주세요.',MODEL_PROVIDER_RESPONSE_INVALID:'공급자가 요청한 구조화 응답을 반환하지 않았습니다.',JEV_CREDENTIAL_REQUIRED:'Jev 키를 입력하거나 사용하지 않음을 선택하세요.',MCP_CLIENT_UNAVAILABLE:'이 WSL/Linux 환경에 클라이언트가 설치되지 않았습니다.',MCP_REGISTRATION_CONFLICT:'기존 agent-driver 설정이 달라 자동으로 덮어쓰지 않았습니다.',MCP_REGISTRATION_FAILED:'클라이언트가 MCP 등록을 완료하지 못했습니다.',OPENCODE_MCP_CONFIG_REVIEW_REQUIRED:'기존 OpenCode 설정을 안전하게 읽지 못해 보존했습니다. 설정 파일을 확인한 뒤 다시 연결하세요.',OPENCODE_MCP_CONFIG_UNSAFE:'OpenCode 설정 파일이 일반 파일이 아니거나 너무 큽니다. 기존 파일은 변경하지 않았습니다.',CLIENT_INSTALL_PLATFORM_UNSUPPORTED:'자동 설치는 Linux·WSL에서 지원합니다. Windows 앱 연결을 선택하세요.',CLIENT_INSTALL_DOWNLOAD_REJECTED:'공식 설치 파일의 주소나 크기를 확인하지 못해 실행하지 않았습니다. 설치를 다시 누르세요.',CLIENT_INSTALL_DOWNLOAD_FAILED:'설치 파일을 내려받지 못했습니다. 인터넷 연결을 확인한 뒤 설치를 다시 누르세요.',CLIENT_INSTALL_DOWNLOAD_TIMEOUT:'설치 파일 다운로드가 지연됐습니다. 인터넷 연결을 확인한 뒤 다시 누르세요.',CLIENT_INSTALL_SCRIPT_INVALID:'올바른 설치 파일이 아니어서 실행하지 않았습니다. 설치를 다시 누르세요.',CLIENT_INSTALL_FAILED:'설치 프로그램이 실패했습니다. 아래 연결 작업 기록에서 종료 코드를 확인하고 다시 누르세요.',CLIENT_INSTALL_TIMEOUT:'설치 시간이 초과됐습니다. 다시 확인으로 설치 여부를 확인하세요.',CLIENT_INSTALL_NOT_DETECTED:'설치 후 실행 파일을 찾지 못했습니다. 다시 확인을 누르거나 설치를 다시 시도하세요.',SETTINGS_REQUEST_INVALID:'요청을 처리하지 못했습니다. 다시 확인 후 재시도하세요.'})[error.message]||error.message);}finally{busy=false;lockControls(!initialized);}}
function modeFields(){const subscription=$('mode').value!=='api';$('api-fields').hidden=subscription;$('subscription-fields').hidden=!subscription;$('codex-model').closest('.row').hidden=!subscription&&modelScope!=='coding';$('catalog-state').hidden=!subscription&&modelScope!=='coding';$('base-url-fields').hidden=$('api-provider').value!=='openai_compatible';scopeFields();}
function jevFields(){$('jev-fields').hidden=$('jev-mode').value!=='on';}
function populate(){const s=state.selection;$('mode').value=s.mode;$('client').value=s.client;$('api-provider').value=s.api_provider;$('api-base-url').value=s.api_base_url||'';fillModels('api-model',apiCatalogProvider===s.api_provider?apiCatalog?.models||[]:[],s.api_model,'모델 선택');for(const id of ['codex','claude','opencode'])fillModels(id+'-model',clientCatalogs[id]?.models||[],s.client_models?.[id]);$('api-model-custom').value='';$('api-to-subscription').checked=s.api_to_subscription??false;$('reasoning').value=s.reasoning;$('jev-mode').value=s.jev;$('api-consent').checked=state.configured&&s.mode==='api';$('api-state').textContent=(state.api_key_present?'키 저장됨':'키 필요')+' · '+(state.api_connection==='ready'?'연결 확인됨':'연결 전');$('jev-state').textContent=state.jev_key_present?'키 저장됨':'키를 입력하세요';$('computer-state').textContent=state.computer.connected?'연결됨':'승인 필요';$('computer-state').className='badge '+(state.computer.connected?'ok':'warn');$('work-data-row').hidden=!state.work_model_data?.editable;$('work-data').checked=Boolean(state.work_model_data?.approved);stepMarks();compactHints(document.body);$('connect-computer').disabled=state.computer.connected;modeFields();jevFields();}
async function show(index){if(!initialized)return;if(modelScope==='coding'&&index!==2)await selectModelScope('global');if(index!==step)notice('');step=index;for(let i=0;i<4;i++)$('step-'+i).hidden=i!==index;document.querySelectorAll('[data-step]').forEach(b=>b.classList.toggle('active',Number(b.dataset.step)===index));$('progress').textContent=(index+1)+' / 4';if(index===1)try{await refreshBrowserSetup();}catch{notice('브라우저 안내를 불러오지 못했습니다. 다시 불러오기를 누르세요.');}if(index===0&&!mcpLoaded){await refreshMcp();mcpLoaded=true;}if(index===2&&!clientsLoaded){await refreshClients();clientsLoaded=true;}}
function formBody(next){if(modelScope==='coding'&&$('coding-inherit').checked)return {revision:state.revision,onboarding_step:next,setup_area:'ai',inherit_global:true,selection:state.selection};const body={revision:state.revision,onboarding_step:next,setup_area:step===3?'jev':'ai',...(modelScope==='coding'?{inherit_global:false}:{}),selection:{mode:$('mode').value,client:$('client').value,client_models:Object.fromEntries(['codex','claude','opencode'].map(id=>[id,$(id+'-model').value||null])),api_to_subscription:$('api-to-subscription').checked,api_provider:$('api-provider').value,api_model:($('api-model-custom').value.trim()||$('api-model').value).trim(),api_base_url:$('api-base-url').value.trim(),reasoning:$('reasoning').value,jev:$('jev-mode').value}};for(const name of modelScope==='coding'?['api']:['api','jev']){const value=$(name+'-key').value.trim();if($('remove-'+name).checked){body[name+'_action']='remove';}else if(value){body[name+'_action']='replace';body[name+'_key']=value;}}return body;}
function needsApiProbe(body){const before=state.selection,after=body.selection;return state.api_connection!=='ready'||body.api_action!==undefined||before.api_provider!==after.api_provider||before.api_model!==after.api_model||before.api_base_url!==after.api_base_url||before.reasoning!==after.reasoning;}
async function save(next=step){const body=formBody(next);if(!body.inherit_global&&$('mode').value==='api'&&!$('api-consent').checked)throw Error('API 사용 요금을 확인해 주세요.');if(!body.inherit_global&&$('mode').value==='api'&&needsApiProbe(body)){notice('API 연결을 확인하는 중…');const probe=await request('settings/provider-probe',body);body.api_probe_token=probe.probe_token;}const updated=await request('settings/save',body);state={...state,...updated};if(modelScope==='global'&&state.work_model_data?.editable&&step===2&&$('work-data').checked!==Boolean(state.work_model_data.approved)){const status=await request('settings/work-data',{approved:$('work-data').checked});state={...state,work_model_data:status.work_model_data};}for(const name of ['api','jev']){$(name+'-key').value='';$('remove-'+name).checked=false;}populate();notice('저장했습니다.');}
async function refreshMcp(){
  notice('설치·로그인·MCP 상태 확인 중…');
  const checked=await request('settings/mcp/check',{});mcpState=checked.mcp;bootstrapState=checked.bootstrap;
  $('driver-state').textContent=mcpState.agent_driver.installed?'설치됨 · MCP 서버 준비됨':'확인 필요';$('driver-state').className='badge '+(mcpState.agent_driver.installed?'ok':'warn');
  const list=$('mcp-clients');list.replaceChildren();
  const registrations=new Map(mcpState.clients.map(item=>[item.id,item]));
  const connections=new Map(bootstrapState.connections.map(item=>[item.id,item]));
  for(const client of bootstrapState.clients){
    const registration=registrations.get(client.id),connection=connections.get(client.id),card=document.createElement('div');card.className='client';card.dataset.client=client.id;
    const stateLabel=!client.installed?'설치 필요':['signed_out','expired'].includes(connection?.status)?'로그인 필요':registration?.registration==='registered'?'MCP 등록됨':registration?.registration==='conflict'?'설정 검토 필요':'MCP 등록 필요',tone=!client.installed?'idle':registration?.registration==='registered'&&!['signed_out','expired'].includes(connection?.status)?'ok':registration?.registration==='conflict'?'err':'warn';
    const row=clientRow(client.label,stateLabel,tone,client.id),actions=row.querySelector('.cact');card.append(row);
    const flow=document.createElement('div');flow.className='device';flow.hidden=true;flow.id='agent-flow-'+client.id;card.append(flow);
    if(!client.installed){
      if(client.managed_install){const install=document.createElement('button');install.textContent='설치';install.setAttribute('aria-label',client.label+' 설치');install.onclick=()=>installAction(client.id);actions.append(install);}
    }else{
      if(['signed_out','expired'].includes(connection?.status)){const kind=connection.supported_login_flows.includes('device')?'device':connection.supported_login_flows[0];if(kind){const login=document.createElement('button');login.textContent='로그인';login.className='login-action';login.setAttribute('aria-label',client.label+' 로그인');login.onclick=()=>loginAction(client.id,kind);actions.append(login);}}
      if(registration?.automatic&&registration.registration==='not_registered'&&!['signed_out','expired','needs_login','challenge'].includes(connection?.status)){const button=document.createElement('button');button.textContent='연결';button.setAttribute('aria-label',client.label+' MCP 연결');button.className='primary';button.onclick=()=>action(async()=>{mcpState=await request('settings/mcp/register',{client:client.id});await refreshMcp();});actions.append(button);}
      if(registration?.registration==='registered'&&connection?.status==='ready')addClientManage(actions,client.id,client.label,true);
    }
    list.append(card);renderFlow(connection?.connection||{client_id:client.id,state:'idle'});
  }
  const bridge=mcpState.windows_bridge;
  $('windows-bridge').hidden=!bridge;
  if(bridge)$('windows-bridge-config').textContent=JSON.stringify({command:bridge.command,args:bridge.args},null,2);
  $('mcp-next').disabled=!(mcpState.registered_count||bridge);stepMarks();compactHints(document.body);
  notice(mcpState.registered_count?'WSL 앱의 MCP 등록을 확인했습니다.':bridge?'위에서 앱을 연결하거나, Windows AI 앱 연결을 선택하세요.':'앱 하나를 설치하고 MCP를 등록하세요.');
}
async function refreshClients(){notice('연결 상태 확인 중…');const [data,models]=await Promise.all([request('settings/refresh',{}),request('settings/models')]);clientCatalogs=models;$('clients').replaceChildren();for(const client of data.clients){const card=document.createElement('div');card.className='client';card.id='client-'+client.id;const name=({codex:'Codex',claude:'Claude Code',opencode:'OpenCode',cursor:'Cursor',hermes:'Hermes'})[client.id],row=clientRow(name,client.reason==='wsl_native_client_not_found'?'설치 안 됨':labels[client.status],client.status==='ready'?'ok':['signed_out','expired','needs_login','challenge'].includes(client.status)?'warn':'idle',client.id),actions=row.querySelector('.cact');card.append(row);const output=document.createElement('div');output.className='device';output.hidden=true;output.id='flow-'+client.id;card.append(output);if(['signed_out','expired'].includes(client.status))for(const flow of [client.supported_login_flows.includes('device')?'device':client.supported_login_flows[0]].filter(Boolean)){const button=document.createElement('button');button.textContent='로그인';button.className='login-action';button.setAttribute('aria-label',client.id+' 로그인');button.onclick=()=>loginAction(client.id,flow);actions.append(button);}if(client.status==='ready')addClientManage(actions,client.id,name);const installation=bootstrapState?.clients?.find(item=>item.id===client.id);if(installation&&!installation.installed&&installation.managed_install){const install=document.createElement('button');install.textContent='설치';install.setAttribute('aria-label',name+' 설치');install.onclick=()=>installAction(client.id);actions.append(install);}$('clients').append(card);renderFlow(client.connection);}for(const id of ['codex','claude','opencode'])fillModels(id+'-model',models[id]?.models||[],$(id+'-model').value);$('catalog-state').textContent='현재 확인: '+['codex','claude','opencode'].map(id=>id+' '+(models[id]?.status==='available'?models[id].models.length+'개':'기본값만')).join(' · ');notice('확인했습니다.');}
async function refreshApiModels(reset=false){const provider=$('api-provider').value,body={provider,api_base_url:$('api-base-url').value.trim()};if($('api-key').value.trim())body.api_key=$('api-key').value.trim();const current=reset?'':$('api-model-custom').value.trim()||$('api-model').value||(state.selection.api_provider===provider?state.selection.api_model:'');body.current=current;const catalog=await request('settings/models',body);if(provider!==$('api-provider').value||body.api_base_url!==$('api-base-url').value.trim())return;apiCatalog=catalog;apiCatalogProvider=provider;fillModels('api-model',catalog.models,catalog.status==='available'?catalog.selected||'':catalog.selected||current,'모델 선택');if(catalog.selected&&catalog.selected!==current)$('api-model-custom').value='';$('api-state').textContent=catalog.status==='available'?catalog.models.length+'개 모델 확인 · '+new Date(catalog.fetched_at).toLocaleString(window.officeLang==='ko'?'ko-KR':'en-GB'):(catalog.models.length?'키 입력 후 새로고침하면 최신 목록을 불러옵니다 · 기본 '+catalog.selected:'모델 목록을 확인하지 못했습니다. 저장된 선택은 유지됩니다.');}
function renderFlow(flow){const url=flow.auth_url||flow.device_url,tab=authWindows.get(flow.client_id);if(url&&tab&&!tab.closed){tab.location.replace(url);authWindows.delete(flow.client_id);}if(['completed','failed','unavailable'].includes(flow.state))closeAuthWindow(flow.client_id);for(const target of [$('flow-'+flow.client_id),$('agent-flow-'+flow.client_id)].filter(Boolean)){if(flow.state==='idle'||flow.state==='unavailable'&&flow.reason==='login_contract_unavailable'){target.hidden=true;target.replaceChildren();continue;}target.hidden=false;target.replaceChildren();const text=document.createElement('span');text.textContent=({starting:'인증 화면 준비 중…',waiting:url?'공식 인증 화면에서 인증을 마쳐주세요.':'인증 화면 준비 중…',completed:'로그인 완료 · 상태를 다시 확인합니다.',failed:'로그인을 완료하지 못했습니다. 로그인 버튼으로 다시 시도하세요.',unavailable:'설치는 유지됩니다. 다시 확인 후 로그인을 다시 누르세요.'})[flow.state]||flow.state;target.append(text);if(url){const link=document.createElement('a');link.href=url;link.target='_blank';link.rel='noreferrer';link.className='action-link';link.textContent='인증 열기';target.append(link);}if(flow.user_code){const code=document.createElement('code');code.textContent=flow.user_code;target.append(code);}}}
async function pollFlows(){try{const data=await request('settings/flows');data.flows.forEach(renderFlow);if(!data.flows.some(f=>['starting','waiting'].includes(f.state))){clearInterval(flowTimer);if(step===0)await refreshMcp();else if(step===2)await refreshClients();}}catch{clearInterval(flowTimer);}}
function appendActivity(event){const ko=window.officeLang==='ko',time=new Date(event.at).toLocaleTimeString(ko?'ko-KR':'en-GB',{hour12:false}),status=(ko?{running:'진행',success:'완료',warning:'확인 필요',error:'실패',info:'기록'}:{running:'running',success:'done',warning:'needs attention',error:'failed',info:'log'})[event.state]||(ko?'기록':'log'),message=window.officeText(event.message);if($('setup-log').dataset.empty==='true'){$('setup-log').textContent='';$('setup-log').dataset.empty='false';}$('setup-log').textContent+=time+' ['+event.area.toUpperCase()+' · '+status+'] '+message+'\\n';$('setup-log').scrollTop=$('setup-log').scrollHeight;$('tail-last').textContent=message;}
const activitySource=new EventSource('settings/activity');activitySource.onopen=()=>{$('tail-state').textContent='실시간 연결됨';};activitySource.onerror=()=>{$('tail-state').textContent='재연결 중';};activitySource.onmessage=message=>{const value=JSON.parse(message.data);if(value.kind==='snapshot'){$('setup-log').textContent='';$('setup-log').dataset.empty='false';if(value.events.length)value.events.forEach(appendActivity);else{$('setup-log').textContent='아직 연결 작업 기록이 없습니다.';$('setup-log').dataset.empty='true';}}else if(value.kind==='activity')appendActivity(value.event);};
document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>action(()=>show(Number(b.dataset.step))));
document.querySelectorAll('[data-next]').forEach(b=>b.onclick=()=>action(()=>show(Number(b.dataset.next))));
document.querySelectorAll('[data-save-next]').forEach(b=>b.onclick=()=>action(async()=>{const next=Number(b.dataset.saveNext);await save(next);await show(next);}));
$('model-scope').onchange=()=>{const scope=$('model-scope').value;void action(()=>selectModelScope(scope));};
$('coding-inherit').onchange=()=>scopeFields();
$('copy-windows-bridge').onclick=()=>action(async()=>{await navigator.clipboard.writeText($('windows-bridge-config').textContent);notice('Windows 앱용 MCP 연결 정보를 복사했습니다. 앱에 등록한 뒤 MCP 목록에서 연결을 확인하세요.');});
$('mode').onchange=()=>{notice('');modeFields();if($('mode').value==='api')void action(refreshApiModels);};
$('jev-mode').onchange=jevFields;
$('api-provider').onchange=()=>{modeFields();apiCatalog=null;apiCatalogProvider=null;$('api-model-custom').value='';fillModels('api-model',[],'','모델 선택');void action(()=>refreshApiModels(true));};
$('refresh-api-models').onclick=()=>action(refreshApiModels);
$('refresh-mcp').onclick=()=>action(refreshMcp);
$('refresh-clients').onclick=()=>action(refreshClients);
$('connect-computer').onclick=()=>action(async()=>{state=await request('settings/computer',{mode:'non_interfering'});populate();await show(2);});
$('save-model').onclick=()=>action(()=>save(Math.max(2,state.onboarding_step)));
$('save-jev').onclick=()=>action(()=>save(Math.max(3,state.onboarding_step)));
$('finish').onclick=()=>action(async()=>{await save(4);location.href='./';});
async function initialize(){lockControls(true);$('retry-settings').hidden=true;notice('설정을 불러오는 중…');try{const [value,mcp,bootstrap]=await Promise.all([request('settings/status'),request('settings/mcp'),request('settings/bootstrap')]);state=value;mcpState=mcp;bootstrapState=bootstrap;initialized=true;populate();notice('');await action(async()=>{await show(!mcp.registered_count&&!state.computer.connected?0:!state.computer.connected?1:Math.min(3,Math.max(2,state.onboarding_step)));if(state.selection.mode==='api')await refreshApiModels();});}catch{initialized=false;lockControls(true);notice('설정을 불러오지 못했습니다. 다시 시도해 주세요.');$('retry-settings').hidden=false;}}
const retrySettings=document.createElement('button');retrySettings.id='retry-settings';retrySettings.textContent='설정 다시 불러오기';retrySettings.hidden=true;retrySettings.onclick=initialize;$('notice').after(retrySettings);
${browserSetupScript}
void initialize();
</script></html>`;}
