import {helpDialogHtml,helpScript,langButtonHtml,sidebarHtml,uiCss} from './ui-shell.js';
import {i18nScript} from './i18n.js';
export function settingsHtml(nonce:string){return `<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>연결 및 설정 · Agent Office</title>
<style>${uiCss}
.flow{display:grid;grid-template-columns:1fr 28px 1.2fr 28px 1fr;align-items:center;margin:0 0 18px}.flow i{height:1px;background:var(--line2)}.nd{border:1px solid var(--line2);border-radius:var(--r);padding:10px 14px;background:var(--panel);min-width:0}.nd b{display:block;font:500 14px var(--mono)}.nd small{font:11.5px var(--mono);color:var(--dim)}.nd.hot{border-color:var(--accent);box-shadow:0 0 0 3px var(--acc-a)}
@media(max-width:700px){.flow{grid-template-columns:1fr}.flow i{width:1px;height:12px;margin:auto}}
.steps4{display:flex;gap:4px;border-bottom:1px solid var(--line);margin:4px 0 14px;overflow-x:auto}.steps4 button{border:0;border-bottom:2px solid transparent;border-radius:0;background:none;color:var(--dim);padding:8px 10px;display:flex;align-items:center;gap:6px}
.steps4 button.active{color:var(--text);border-bottom-color:var(--accent);font-weight:600}.si{width:16px;height:16px;border-radius:50%;border:1px solid var(--line2);font-size:10px;line-height:14px;text-align:center;color:var(--faint)}.si.done{background:var(--ok);border-color:var(--ok);color:var(--bg)}
.settings{max-width:760px}.panel h2{font-size:16px;margin-bottom:4px}.panel>p.muted{margin:0 0 10px}
.runtime-line{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:10px 0;border-bottom:1px solid var(--line)}
.list{display:flex;flex-direction:column}.client{padding:10px 0;border-bottom:1px solid var(--line)}.crow{display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap}
.client strong{display:flex;align-items:center;gap:10px;font-weight:500}.client .sep{font-size:0}.client .cname{min-width:96px}.cact{display:flex;gap:6px;align-items:center;flex-wrap:wrap}.cact a{font-size:12px}
.client p{margin:4px 0 0;font-size:12px}.client p.muted.hinted{display:none}
.device{margin-top:8px;padding:8px 10px;background:var(--raise);border-radius:6px;overflow-wrap:anywhere;font-size:13px}.device code{display:block;font-size:20px;margin-top:6px;letter-spacing:.08em}
.row{display:flex;gap:10px;flex-wrap:wrap}.row>*{flex:1;min-width:160px}.actions{display:flex;gap:8px;justify-content:flex-end;margin-top:16px;flex-wrap:wrap}
details{margin-top:12px;color:var(--dim)}details summary{cursor:pointer}details label{color:var(--text)}#windows-bridge-config{white-space:pre-wrap;overflow-wrap:anywhere}
.consent{margin-top:14px;padding:10px 12px;border:1px solid var(--line);border-radius:6px}.consent label{margin:0;color:var(--text)}
.terminal{margin:14px 0 0;border:1px solid var(--line);border-radius:var(--r);background:var(--panel)}.terminal-head{display:flex;justify-content:space-between;gap:10px;padding:8px 12px;font-size:12px;color:var(--dim);cursor:pointer;list-style:none}.terminal-head::-webkit-details-marker{display:none}
#tail-last{flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--faint)}.terminal pre{margin:0;padding:10px 12px;max-height:220px;overflow:auto;white-space:pre-wrap;overflow-wrap:anywhere;border-top:1px solid var(--line);color:var(--dim)}
#clients{flex-direction:row;flex-wrap:wrap;gap:6px;margin:10px 0 4px}#clients .client{border:1px solid var(--line);border-radius:6px;padding:5px 8px}#clients .cname{min-width:0}#clients .cact:empty{display:none}#refresh-clients{margin-top:6px}
@media(max-width:520px){.actions button{flex:1}.client .cname{min-width:0}}</style>
<div class="app">${sidebarHtml('settings')}<main class="main"><div class="settings"><header class="top"><h1>연결 및 설정</h1><span class="muted mono" id="progress">설정을 불러오는 중…</span>${langButtonHtml}</header><div class="flow" aria-hidden="true"><div class="nd"><b>mcp client</b><small>claude code · codex · cursor · hermes</small></div><i></i><div class="nd hot"><b>agent-office mcp</b><small>stdio · observe · pack plan</small></div><i></i><div class="nd"><b>LOCAL</b><small>no cloud relay</small></div></div><nav class="steps4" aria-label="설정 단계"><button data-step="0"><span class="si" id="si-0" aria-hidden="true">1</span>에이전트</button><button data-step="1"><span class="si" id="si-1" aria-hidden="true">2</span>로컬 실행</button><button data-step="2"><span class="si" id="si-2" aria-hidden="true">3</span>AI</button><button data-step="3"><span class="si" id="si-3" aria-hidden="true">4</span>Jev</button></nav>
<section class="panel" id="step-0" hidden><h2>에이전트 연결</h2><p class="muted">업무를 맡길 앱을 연결하세요. 앱이 없으면 여기에서 설치와 로그인, MCP 등록을 진행할 수 있습니다.</p><div class="runtime-line"><strong>Agent Office 런타임</strong><span class="badge idle" id="driver-state">설치 확인 중</span></div><div id="mcp-clients" class="list"></div><details id="windows-bridge" hidden><summary>Windows 앱에서 연결하기</summary><p class="muted">Windows에 설치한 앱의 MCP stdio 설정에 아래 명령과 인수를 등록하세요. WSL의 같은 사용자로 실행되며, 등록 여부는 이 화면에서 자동 확인되지 않습니다.</p><pre class="device" id="windows-bridge-config"></pre><button id="copy-windows-bridge">연결 정보 복사</button></details><div class="actions"><button id="refresh-mcp">다시 확인</button><button id="mcp-next" data-next="1" class="primary">다음</button></div></section>
<section class="panel" id="step-1" hidden><h2>로컬 실행</h2><p class="muted">업무가 이어질 전용 환경을 연결합니다. 이 연결은 내 화면을 빼앗지 않으며, 업무별 진행 상황은 업무 현황에서 확인합니다.</p><div class="runtime-line"><strong>전용 작업 환경</strong><span class="badge idle" id="computer-state"></span></div><div class="actions"><button id="connect-computer" class="primary">로컬 실행 승인</button><button data-next="2">다음</button></div></section>
<section class="panel" id="step-2" hidden><h2>AI 연결</h2><p class="muted">사용 중인 구독이나 API 키를 선택하세요. 선택한 앱을 먼저 사용하고, 인계 시 받는 앱에 저장한 모델을 적용합니다.</p><label for="mode">연결 방식</label><select id="mode"><option value="subscription">구독 사용</option><option value="api">API 키 사용</option></select><div id="subscription-fields"><label for="client">우선 사용할 클라이언트</label><select id="client"><option value="auto">자동 선택</option><option value="mcp">연결된 MCP 클라이언트</option><option value="codex">Codex</option><option value="claude">Claude Code</option><option value="opencode">OpenCode</option></select><button id="refresh-clients">연결 상태 확인</button><div id="clients" class="list"></div></div><div class="row"><div><label for="codex-model">Codex 모델</label><select id="codex-model"><option value="">클라이언트 기본값</option></select></div><div><label for="claude-model">Claude Code 모델</label><select id="claude-model"><option value="">클라이언트 기본값</option></select></div><div><label for="opencode-model">OpenCode 모델</label><select id="opencode-model"><option value="">클라이언트 기본값</option></select></div></div><p class="muted keep" id="catalog-state">모델 목록은 연결된 앱에서 확인합니다. 기본값은 앱 업데이트를 따릅니다.</p>
<div id="api-fields" hidden><div class="row"><div><label for="api-provider">공급자</label><select id="api-provider"><option value="openai">OpenAI</option><option value="anthropic">Anthropic</option><option value="openrouter">OpenRouter</option><option value="openai_compatible">OpenAI 호환 서버</option></select></div><div><label for="reasoning">추론 강도</label><select id="reasoning"><option>low</option><option>medium</option><option>high</option></select></div></div><div id="base-url-fields" hidden><label for="api-base-url">API 주소</label><input id="api-base-url" type="url" placeholder="https://provider.example/v1"></div><label for="api-model">모델</label><select id="api-model"></select><button id="refresh-api-models">현재 모델 목록 새로고침</button><label for="api-model-custom">목록에 없는 모델 ID</label><input id="api-model-custom" maxlength="200" placeholder="직접 입력 시 목록 선택보다 우선"><label for="api-key">API 키</label><input id="api-key" type="password" autocomplete="new-password" placeholder="키 입력"><p class="muted" id="api-state"></p><label><input id="api-consent" type="checkbox"> API 사용 요금을 확인했습니다.</label><label><input id="api-to-subscription" type="checkbox"> API 인증·한도 오류 시 연결된 구독 앱으로 이어가기</label><details><summary>저장된 키 관리</summary><label><input type="checkbox" id="remove-api"> 저장된 API 키 삭제</label></details></div><div class="consent" id="work-data-row" hidden><label><input id="work-data" type="checkbox"> 업무 내용을 선택한 AI로 보내 정의·계획하도록 허용</label><p class="muted">한 줄 업무와 가져온 자료의 요약을 선택한 구독 앱이나 API 모델로 보냅니다. 끄면 업무는 저장되지만 AI 정의 단계에서 멈춥니다. 로컬 runtime-config.json의 work.model_data_approved에 기록됩니다.</p></div><div class="actions"><button id="save-model">저장</button><button data-save-next="3" class="primary">다음</button></div></section>
<section class="panel" id="step-3" hidden><h2>Jev 연결</h2><p class="muted">빠른 반복 판단에 사용합니다. 연결하지 않아도 LLM으로 진행합니다.</p><label for="jev-mode">사용 방식</label><select id="jev-mode"><option value="inherit">자동</option><option value="off">사용하지 않음</option><option value="on">API 키로 연결</option></select><div id="jev-fields" hidden><label for="jev-key">TypeSafe / Jev API 키</label><input id="jev-key" type="password" autocomplete="new-password" placeholder="키 입력"><p id="jev-state" class="muted"></p><details><summary>저장된 키 관리</summary><label><input type="checkbox" id="remove-jev"> 저장된 Jev 키 삭제</label></details></div><div class="actions"><button id="save-jev">저장</button><button id="finish" class="primary">완료</button></div></section>
<p class="notice" role="status" aria-live="polite" id="notice"></p><details class="terminal" aria-label="연결 작업 기록"><summary class="terminal-head"><span>연결 작업 기록</span><span id="tail-last"></span><span id="tail-state">연결 중</span></summary><p class="muted" style="margin:12px 14px 0;font-size:13px">이 화면에서 실행한 설치·연결의 시작과 결과입니다. 터미널 원문은 저장하지 않습니다. 실제 업무 기록은 <a href="./">업무 현황</a>의 업무 상세에서 확인하세요.</p><pre id="setup-log" aria-live="polite">아직 연결 작업 기록이 없습니다.</pre></details></div></main></div>${helpDialogHtml}
<script nonce="${nonce}">
${i18nScript}
${helpScript}
const $=id=>document.getElementById(id);let state,mcpState,bootstrapState,step=0,busy=false,flowTimer,clientsLoaded=false,mcpLoaded=false,clientCatalogs={},apiCatalog=null,apiCatalogProvider=null;
function fillModels(id,models,selected,defaultLabel='클라이언트 기본값'){const field=$(id);field.replaceChildren();const first=document.createElement('option');first.value='';first.textContent=defaultLabel;field.append(first);for(const row of models){const item=document.createElement('option');item.value=row.id;item.textContent=row.label===row.id?row.id:row.label+' · '+row.id;field.append(item);}if(selected&&!models.some(row=>row.id===selected)){const item=document.createElement('option');item.value=selected;item.textContent=selected+' · 저장된 모델';field.append(item);}field.value=selected||'';}
const notice=text=>$('notice').textContent=text;
function clientRow(name,stateLabel,tone){const row=document.createElement('div');row.className='crow';const title=document.createElement('strong'),n=document.createElement('span'),sep=document.createElement('span'),badge=document.createElement('span'),actions=document.createElement('div');n.className='cname';n.textContent=name;sep.className='sep';sep.textContent=' · ';badge.className='badge '+tone;badge.textContent=stateLabel;title.append(n,sep,badge);actions.className='cact';row.append(title,actions);return row}
function stepMarks(){const done=[Boolean(mcpState?.registered_count),Boolean(state?.computer?.connected),Boolean(state?.configured&&state.onboarding_step>=3),Boolean(state?.configured&&state.onboarding_step>=4)];done.forEach((ok,i)=>{const m=$('si-'+i);if(m){m.classList.toggle('done',ok);m.textContent=ok?'✓':String(i+1)}})}
const labels={ready:'연결됨',signed_out:'로그인 필요',expired:'다시 로그인 필요',unavailable:'사용할 수 없음',unknown:'확인되지 않음',unchecked:'미확인',needs_login:'로그인 필요',challenge:'사람 확인 필요',retry_requested:'재확인 요청됨',policy_blocked:'미확인'};
async function request(path,body,site=false){const response=await fetch(path,{cache:'no-store',...(body===undefined?{}:{method:'POST',headers:{'content-type':'application/json','X-Agent-Driver':site?'human-connection':'human-settings'},body:JSON.stringify(body)})});const data=await response.json();if(!response.ok)throw Error(data.error||'연결 오류');return data;}
async function action(fn){if(busy)return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();}catch(error){notice(({MODEL_SETTINGS_CONFLICT:'다른 창에서 설정이 바뀌었습니다. 새로고침 후 다시 저장하세요.',MODEL_PROVIDER_CREDENTIAL_REQUIRED:'선택한 공급자의 API 키를 입력하거나 구독 방식으로 전환하세요.',MODEL_PROVIDER_PROBE_REQUIRED:'API 연결 확인이 만료되었거나 설정이 바뀌었습니다. 다시 확인해 주세요.',MODEL_PROVIDER_UNAVAILABLE:'공급자 연결·키·모델을 확인해 주세요.',MODEL_PROVIDER_RESPONSE_INVALID:'공급자가 요청한 구조화 응답을 반환하지 않았습니다.',JEV_CREDENTIAL_REQUIRED:'Jev 키를 입력하거나 사용하지 않음을 선택하세요.',MCP_CLIENT_UNAVAILABLE:'이 WSL/Linux 환경에 클라이언트가 설치되지 않았습니다.',MCP_REGISTRATION_CONFLICT:'기존 agent-driver 설정이 달라 자동으로 덮어쓰지 않았습니다.',MCP_REGISTRATION_FAILED:'클라이언트가 MCP 등록을 완료하지 못했습니다.',CLIENT_INSTALL_PLATFORM_UNSUPPORTED:'이 환경에서는 화면 설치를 지원하지 않습니다. 공식 안내를 이용하세요.',CLIENT_INSTALL_DOWNLOAD_REJECTED:'공식 설치 프로그램을 안전하게 내려받지 못했습니다.',CLIENT_INSTALL_SCRIPT_INVALID:'받은 설치 프로그램을 실행하지 않았습니다.',CLIENT_INSTALL_FAILED:'설치 프로그램이 완료되지 않았습니다.',CLIENT_INSTALL_NOT_DETECTED:'설치는 끝났지만 앱을 찾지 못했습니다. 설치 안내의 PATH 항목을 확인하세요.',SETTINGS_REQUEST_INVALID:'입력값을 확인해 주세요.'})[error.message]||error.message);}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);$('connect-computer').disabled=state?.computer.connected??true;if($('mcp-next'))$('mcp-next').disabled=!(mcpState?.registered_count||mcpState?.windows_bridge);}}
function modeFields(){const subscription=$('mode').value!=='api';$('api-fields').hidden=subscription;$('subscription-fields').hidden=!subscription;$('codex-model').closest('.row').hidden=!subscription;$('catalog-state').hidden=!subscription;$('base-url-fields').hidden=$('api-provider').value!=='openai_compatible';}
function jevFields(){$('jev-fields').hidden=$('jev-mode').value!=='on';}
function populate(){const s=state.selection;$('mode').value=s.mode;$('client').value=s.client;$('api-provider').value=s.api_provider;$('api-base-url').value=s.api_base_url||'';fillModels('api-model',apiCatalogProvider===s.api_provider?apiCatalog?.models||[]:[],s.api_model,'모델 선택');for(const id of ['codex','claude','opencode'])fillModels(id+'-model',clientCatalogs[id]?.models||[],s.client_models?.[id]);$('api-model-custom').value='';$('api-to-subscription').checked=s.api_to_subscription??false;$('reasoning').value=s.reasoning;$('jev-mode').value=s.jev;$('api-consent').checked=state.configured&&s.mode==='api';$('api-state').textContent=(state.api_key_present?'키 저장됨':'키 필요')+' · '+(state.api_connection==='ready'?'연결 확인됨':'연결 전');$('jev-state').textContent=state.jev_key_present?'키 저장됨':'키를 입력하세요';$('computer-state').textContent=state.computer.connected?'연결됨':'승인 필요';$('computer-state').className='badge '+(state.computer.connected?'ok':'warn');$('work-data-row').hidden=!state.work_model_data?.editable;$('work-data').checked=state.work_model_data?.approved||!state.configured;stepMarks();compactHints(document.body);$('connect-computer').disabled=state.computer.connected;modeFields();jevFields();}
function show(index){if(index!==step)notice('');step=index;for(let i=0;i<4;i++)$('step-'+i).hidden=i!==index;document.querySelectorAll('[data-step]').forEach(b=>b.classList.toggle('active',Number(b.dataset.step)===index));$('progress').textContent=(index+1)+' / 4';if(index===0&&!mcpLoaded){mcpLoaded=true;setTimeout(()=>action(refreshMcp),0);}if(index===2&&!clientsLoaded){clientsLoaded=true;setTimeout(()=>action(refreshClients),0);}}
function formBody(next){const body={revision:state.revision,onboarding_step:next,setup_area:step===3?'jev':'ai',selection:{mode:$('mode').value,client:$('client').value,client_models:Object.fromEntries(['codex','claude','opencode'].map(id=>[id,$(id+'-model').value||null])),api_to_subscription:$('api-to-subscription').checked,api_provider:$('api-provider').value,api_model:($('api-model-custom').value.trim()||$('api-model').value).trim(),api_base_url:$('api-base-url').value.trim(),reasoning:$('reasoning').value,jev:$('jev-mode').value}};for(const name of ['api','jev']){const value=$(name+'-key').value.trim();if($('remove-'+name).checked){body[name+'_action']='remove';}else if(value){body[name+'_action']='replace';body[name+'_key']=value;}}return body;}
function needsApiProbe(body){const before=state.selection,after=body.selection;return state.api_connection!=='ready'||body.api_action!==undefined||before.api_provider!==after.api_provider||before.api_model!==after.api_model||before.api_base_url!==after.api_base_url||before.reasoning!==after.reasoning;}
async function save(next=step){if($('mode').value==='api'&&!$('api-consent').checked)throw Error('API 사용 요금을 확인해 주세요.');const body=formBody(next);if($('mode').value==='api'&&needsApiProbe(body)){notice('API 연결을 확인하는 중…');const probe=await request('settings/provider-probe',body);body.api_probe_token=probe.probe_token;}const updated=await request('settings/save',body);state={...state,...updated};if(state.work_model_data?.editable&&step===2&&$('work-data').checked!==Boolean(state.work_model_data.approved)){const status=await request('settings/work-data',{approved:$('work-data').checked});state={...state,work_model_data:status.work_model_data};}for(const name of ['api','jev']){$(name+'-key').value='';$('remove-'+name).checked=false;}populate();notice('저장했습니다.');}
async function refreshMcp(){
  notice('설치·로그인·MCP 상태 확인 중…');
  [mcpState,bootstrapState]=await Promise.all([request('settings/mcp'),request('settings/bootstrap')]);
  $('driver-state').textContent=mcpState.agent_driver.installed?'설치됨 · MCP 서버 준비됨':'확인 필요';$('driver-state').className='badge '+(mcpState.agent_driver.installed?'ok':'warn');
  const list=$('mcp-clients');list.replaceChildren();
  const registrations=new Map(mcpState.clients.map(item=>[item.id,item]));
  const connections=new Map(bootstrapState.connections.map(item=>[item.id,item]));
  for(const client of bootstrapState.clients){
    const registration=registrations.get(client.id),connection=connections.get(client.id),card=document.createElement('div');card.className='client';
    const stateLabel=!client.installed?'설치 필요':['signed_out','expired'].includes(connection?.status)?'로그인 필요':registration?.registration==='registered'?'MCP 등록됨':registration?.registration==='conflict'?'설정 검토 필요':'MCP 등록 필요',tone=!client.installed?'idle':registration?.registration==='registered'&&!['signed_out','expired'].includes(connection?.status)?'ok':registration?.registration==='conflict'?'err':'warn';
    const row=clientRow(client.label,stateLabel,tone),actions=row.querySelector('.cact');card.append(row);
    const desc=document.createElement('p');desc.className='muted';desc.textContent=!client.installed?'':registration?.registration==='registered'?'앱을 다시 열거나 MCP 목록을 새로고침하면 연결됩니다.':connection?.status==='ready'?'로그인 확인됨 · MCP를 연결하면 준비가 끝납니다.':'공식 로그인은 이 앱이 관리하며 Agent Driver는 토큰을 읽지 않습니다.';if(desc.textContent)card.append(desc);
    const flow=document.createElement('div');flow.className='device';flow.hidden=true;flow.id='agent-flow-'+client.id;card.append(flow);
    if(!client.installed){
      if(client.managed_install){const install=document.createElement('button');install.textContent=client.label+' 설치';install.onclick=()=>action(async()=>{await request('settings/client/install',{client:client.id});await refreshMcp();});actions.append(install);}
      const guide=document.createElement('a');guide.href=client.docs_url;guide.target='_blank';guide.rel='noreferrer';guide.textContent='공식 설치 안내';actions.append(guide);
    }else{
      if(['signed_out','expired'].includes(connection?.status))for(const kind of connection.supported_login_flows){const login=document.createElement('button');login.textContent=kind==='device'?'기기 코드로 로그인':'로그인';login.onclick=()=>action(async()=>{const started=await request('settings/login',{client:client.id,flow:kind});renderFlow(started);clearInterval(flowTimer);flowTimer=setInterval(pollFlows,1200);});actions.append(login);}
      if(!connection?.supported_login_flows?.length&&connection?.status!=='ready'){const auth=document.createElement('a');auth.href=client.auth_guide_url;auth.target='_blank';auth.rel='noreferrer';auth.textContent='로그인 안내';actions.append(auth);}
      if(registration?.automatic&&registration.registration==='not_registered'){const button=document.createElement('button');button.textContent=client.label+'에 MCP 등록';button.className='primary';button.onclick=()=>action(async()=>{mcpState=await request('settings/mcp/register',{client:client.id});await refreshMcp();});actions.append(button);}
    }
    list.append(card);renderFlow(connection?.connection||{client_id:client.id,state:'idle'});
  }
  const bridge=mcpState.windows_bridge;
  $('windows-bridge').hidden=!bridge;
  if(bridge)$('windows-bridge-config').textContent=JSON.stringify({command:bridge.command,args:bridge.args},null,2);
  $('mcp-next').disabled=!(mcpState.registered_count||bridge);stepMarks();compactHints(document.body);
  notice(mcpState.registered_count?'WSL 앱의 MCP 등록을 확인했습니다.':bridge?'WSL 앱이 없다면 Windows 앱에 연결 정보를 등록하고 계속하세요. 등록 여부는 아직 확인되지 않았습니다.':'앱 하나를 설치하고 MCP를 등록하세요.');
}
async function refreshClients(){notice('연결 상태 확인 중…');const [data,models]=await Promise.all([request('settings/refresh',{}),request('settings/models')]);clientCatalogs=models;$('clients').replaceChildren();for(const client of data.clients){const card=document.createElement('div');card.className='client';card.id='client-'+client.id;const row=clientRow(({codex:'Codex',claude:'Claude Code',opencode:'OpenCode',cursor:'Cursor',hermes:'Hermes'})[client.id],client.reason==='wsl_native_client_not_found'?'설치 안 됨':labels[client.status],client.status==='ready'?'ok':['signed_out','expired','needs_login','challenge'].includes(client.status)?'warn':'idle'),actions=row.querySelector('.cact');card.append(row);const output=document.createElement('div');output.className='device';output.hidden=true;output.id='flow-'+client.id;card.append(output);if(['signed_out','expired'].includes(client.status))for(const flow of client.supported_login_flows){const button=document.createElement('button');button.textContent=flow==='device'?'기기 코드로 로그인':'로그인';button.onclick=()=>action(async()=>{const started=await request('settings/login',{client:client.id,flow});renderFlow(started);clearInterval(flowTimer);flowTimer=setInterval(pollFlows,1200);});actions.append(button);}$('clients').append(card);renderFlow(client.connection);}for(const id of ['codex','claude','opencode'])fillModels(id+'-model',models[id]?.models||[],$(id+'-model').value);$('catalog-state').textContent='현재 확인: '+['codex','claude','opencode'].map(id=>id+' '+(models[id]?.status==='available'?models[id].models.length+'개':'기본값만')).join(' · ');notice('확인했습니다.');}
async function refreshApiModels(reset=false){const provider=$('api-provider').value,body={provider,api_base_url:$('api-base-url').value.trim()};if($('api-key').value.trim())body.api_key=$('api-key').value.trim();const current=reset?'':$('api-model-custom').value.trim()||$('api-model').value||(state.selection.api_provider===provider?state.selection.api_model:'');body.current=current;const catalog=await request('settings/models',body);apiCatalog=catalog;apiCatalogProvider=provider;fillModels('api-model',catalog.models,catalog.selected||current,'모델 선택');if(catalog.selected&&catalog.selected!==current)$('api-model-custom').value='';$('api-state').textContent=catalog.status==='available'?catalog.models.length+'개 모델 확인 · '+new Date(catalog.fetched_at).toLocaleString(window.officeLang==='ko'?'ko-KR':'en-GB'):(catalog.models.length?'키 입력 후 새로고침하면 최신 목록을 불러옵니다 · 기본 '+catalog.selected:'모델 목록을 확인하지 못했습니다. 저장된 선택은 유지됩니다.');}
function renderFlow(flow){for(const target of [$('flow-'+flow.client_id),$('agent-flow-'+flow.client_id)].filter(Boolean)){if(['idle','unavailable'].includes(flow.state)){target.hidden=true;target.replaceChildren();continue;}target.hidden=false;target.replaceChildren();const text=document.createElement('span');text.textContent=({starting:'로그인 시작 중',waiting:'공식 인증 화면에서 인증을 마쳐주세요.',completed:'로그인 완료 · 상태를 다시 확인합니다.',failed:'연결 실패 · 다시 시도하세요.'})[flow.state]||flow.state;target.append(text);if(flow.device_url){const link=document.createElement('a');link.href=flow.device_url;link.target='_blank';link.rel='noreferrer';link.textContent=' 인증 페이지 열기';target.append(link);}if(flow.user_code){const code=document.createElement('code');code.textContent=flow.user_code;target.append(code);}}}
async function pollFlows(){try{const data=await request('settings/flows');data.flows.forEach(renderFlow);if(!data.flows.some(f=>['starting','waiting'].includes(f.state))){clearInterval(flowTimer);if(step===0)await refreshMcp();}}catch{clearInterval(flowTimer);}}
function appendActivity(event){const time=new Date(event.at).toLocaleTimeString(window.officeLang==='ko'?'ko-KR':'en-GB',{hour12:false}),status=({running:'진행',success:'완료',error:'실패'})[event.state]||'기록';if($('setup-log').dataset.empty==='true'){$('setup-log').textContent='';$('setup-log').dataset.empty='false';}$('setup-log').textContent+=time+' ['+event.area.toUpperCase()+' · '+status+'] '+event.message+'\\n';$('setup-log').scrollTop=$('setup-log').scrollHeight;$('tail-last').textContent=event.message;}
const activitySource=new EventSource('settings/activity');activitySource.onopen=()=>{$('tail-state').textContent='실시간 연결됨';};activitySource.onerror=()=>{$('tail-state').textContent='재연결 중';};activitySource.onmessage=message=>{const value=JSON.parse(message.data);if(value.kind==='snapshot'){$('setup-log').textContent='';$('setup-log').dataset.empty='false';if(value.events.length)value.events.forEach(appendActivity);else{$('setup-log').textContent='아직 연결 작업 기록이 없습니다.';$('setup-log').dataset.empty='true';}}else if(value.kind==='activity')appendActivity(value.event);};
document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>show(Number(b.dataset.step)));
document.querySelectorAll('[data-next]').forEach(b=>b.onclick=()=>show(Number(b.dataset.next)));
document.querySelectorAll('[data-save-next]').forEach(b=>b.onclick=()=>action(async()=>{const next=Number(b.dataset.saveNext);await save(next);show(next);}));
$('copy-windows-bridge').onclick=()=>action(async()=>{await navigator.clipboard.writeText($('windows-bridge-config').textContent);notice('Windows 앱용 MCP 연결 정보를 복사했습니다. 앱에 등록한 뒤 MCP 목록에서 연결을 확인하세요.');});
$('mode').onchange=()=>{notice('');modeFields();if($('mode').value==='api')void action(refreshApiModels);};
$('jev-mode').onchange=jevFields;
$('api-provider').onchange=()=>{modeFields();apiCatalog=null;apiCatalogProvider=null;$('api-model-custom').value='';fillModels('api-model',[],'','모델 선택');void action(()=>refreshApiModels(true));};
$('refresh-api-models').onclick=()=>action(refreshApiModels);
$('refresh-mcp').onclick=()=>action(refreshMcp);
$('refresh-clients').onclick=()=>action(refreshClients);
$('connect-computer').onclick=()=>action(async()=>{state=await request('settings/computer',{mode:'non_interfering'});populate();show(2);});
$('save-model').onclick=()=>action(()=>save(Math.max(2,state.onboarding_step)));
$('save-jev').onclick=()=>action(()=>save(Math.max(3,state.onboarding_step)));
$('finish').onclick=()=>action(async()=>{await save(4);location.href='./';});
Promise.all([request('settings/status'),request('settings/mcp'),request('settings/bootstrap')]).then(([value,mcp,bootstrap])=>{state=value;mcpState=mcp;bootstrapState=bootstrap;populate();show(!mcp.registered_count&&!state.computer.connected?0:!state.computer.connected?1:Math.min(3,Math.max(2,state.onboarding_step)));if(state.selection.mode==='api')void action(refreshApiModels);}).catch(()=>notice('설정을 불러오지 못했습니다.'));
</script></html>`;}
