/** Original-runtime connection uses registered bridges and never launches a second bot. */
export function workAdoptionScript(){return `
let adoptionBusy=false,adoptionTargets=[],adoptionTargetsWork='',adoptionChoice='',adoptionDraft='',adoptionCost=false,adoptionRequestId=null;
const adoptionText=(ko,en)=>window.officeLang==='ko'?ko:en;
function adoptionError(code){const errors={WORK_ADOPTION_TARGET_CHANGED:['연결 상태가 바뀌었습니다. 목록을 다시 확인하세요.','The connection changed. Reload the list.'],WORK_ADOPTION_TARGET_ALREADY_BOUND:['이미 다른 업무에 연결된 실행 환경입니다.','This runtime is already bound to another work.'],WORK_ADOPTION_BINDING_CHANGED:['원본 실행 연결이 변경되었습니다. 연결 설정을 확인하세요.','The original runtime binding changed. Check its configuration.'],WORK_ADOPTION_ACTION_UNSUPPORTED:['이 연결은 해당 제어를 지원하지 않습니다.','This connection does not support that action.'],WORK_REVISION_CONFLICT:['업무 상태가 바뀌었습니다. 최신 상태에서 다시 시도하세요.','The work state changed. Refresh before retrying.']};const text=errors[code];return text?adoptionText(...text):code}
async function adoptionPost(route,body){const response=await fetch('work/adoption/'+route,{method:'POST',headers:{'content-type':'application/json','x-agent-driver':'human-office'},body:JSON.stringify(body)}),data=await response.json();if(!response.ok)throw Error(adoptionError(data.error||'WORK_ADOPTION_REQUEST_FAILED'));return data}
function workAdoptionHtml(d){
 if(!d.adoption&&!d.imported_connection&&!d.adoption_eligible)return '';
 const text=adoptionText,a=d.adoption;
 let html='<section id="office-work-adoption" class="jev-setting" data-i18n-skip><h4>'+text('원본 실행 연결','Original runtime')+'</h4>';
 if(!a){
   const choices=adoptionTargetsWork===d.id?adoptionTargets:[];
   html+='<p>'+text('기존에 등록된 실행 연결을 선택하세요.','Choose a registered runtime connection.')+'</p><label for="adoption-target">'+text('실행 연결','Runtime connection')+'</label><select id="adoption-target" '+(!choices.length?'disabled':'')+'><option value="">'+text('연결 선택','Choose connection')+'</option>'+choices.map(t=>'<option value="'+esc(t.id)+'" '+(adoptionChoice===t.id?'selected':'')+'>'+esc(t.title)+' · '+esc(t.runtime==='hermes'?'Hermes':'OpenClaw')+(t.scope==='original_remote_job'?' · '+text('조회 전용','Read only'):'')+'</option>').join('')+'</select><div class="controls action-grid"><button type="button" id="adoption-targets" '+(adoptionBusy?'disabled':'')+'>'+text('연결 찾기','Find connections')+'</button><button type="button" id="adoption-bind" class="primary" '+(adoptionBusy||!adoptionChoice?'disabled':'')+'>'+text('연결','Connect')+'</button></div>';
   if(adoptionTargetsWork===d.id&&!choices.length)html+='<p role="status">'+text('등록된 실행 연결이 없습니다. 아래 가져오기에서 Hermes 또는 원격 서버의 업무를 연결하세요.','No registered runtime is available. Connect a Hermes or remote server work from Import.')+'</p><a href="?import=1">'+text('실행 연결 등록','Register runtime connection')+'</a>';
 }else{
   const c=a.capabilities;
   html+='<p>'+esc(a.target_title||a.runtime)+' · '+esc((window.officeText||String)(labels[a.state]||a.state))+'</p><p class="muted">'+text('마지막 확인','Last observed')+' '+esc(a.observed_at||text('아직 없음','Not yet observed'))+'</p><div class="controls action-grid">'+(c.observe?'<button type="button" data-adoption-action="refresh">'+text('상태 확인','Check status')+'</button>':'')+(c.pause?'<button type="button" data-adoption-action="pause">'+text('일시정지','Pause')+'</button>':'')+(c.resume?'<button type="button" data-adoption-action="resume">'+text('재개','Resume')+'</button>':'')+(c.review?'<button type="button" data-adoption-action="review">'+text('결과 확인','Review result')+'</button>':'')+'</div>';
   if(a.connection==='binding_changed')html+='<p role="alert">'+text('실행 연결의 설정이 바뀌었습니다. 원본 연결을 확인하세요.','The runtime configuration changed. Review the original connection.')+'</p>';
   if(c.send)html+='<label for="adoption-instruction">'+text('다음 지시','Next instruction')+'</label><textarea id="adoption-instruction" maxlength="4000">'+esc(adoptionDraft)+'</textarea><label><input id="adoption-cost" type="checkbox" '+(adoptionCost?'checked':'')+'> '+text('연결된 모델의 사용량이 발생할 수 있음을 확인했습니다.','I understand this uses the connected model allowance.')+'</label><div class="controls action-grid"><button type="button" id="adoption-send" class="primary" '+(adoptionBusy||!adoptionCost?'disabled':'')+'>'+text('지시 전달','Send instruction')+'</button></div>';
   if(a.snapshot?.permission)html+='<article class="coding-reconcile"><h4>'+text('사용자 확인 필요','Your confirmation is needed')+'</h4><p>'+esc(a.snapshot.permission.title)+'</p><div class="controls action-grid">'+a.snapshot.permission.options.map(o=>'<button type="button" data-adoption-option="'+esc(o.id)+'">'+esc(o.label)+'</button>').join('')+'</div></article>';
   if(a.snapshot?.reply)html+='<details><summary>'+text('최근 답변','Latest reply')+'</summary><pre style="white-space:pre-wrap;overflow-wrap:anywhere">'+esc(a.snapshot.reply)+'</pre></details>';
 }
 html+='<details><summary>'+text('설명 보기','Show explanation')+'</summary><p>'+text('연결하면 원본 실행의 기록과 지원되는 제어를 이 업무에서 확인합니다. 기존 봇·예약·전달 경로는 원래 환경에서 유지됩니다.','Connect to view the original execution records and supported controls here. Existing bots, schedules and delivery stay in their original environment.')+'</p>'+(a?.scope==='office_managed_session'?'<p>'+text('Hermes 연결은 Office에 등록된 세션만 제어합니다. 별도로 실행 중인 봇과 예약은 자동 제어하지 않습니다.','The Hermes bridge controls its registered Office session. Independently running bots and schedules are not controlled automatically.'):'')+(a?.scope==='original_remote_job'?'<p>'+text('이 예약 연결은 실행 기록만 조회합니다. 예약 실행·중단은 원본 서버가 관리합니다.','This job connection reads execution records. Its original server manages running and stopping the schedule.'):'')+'</details></section>';
 return html;
}
function workMigrationNoticeHtml(d){if(d.imported_execution_owner!=='office'||d.spec?.recurrence?.kind!=='recurring')return '';return '<p id="office-work-migration-notice" class="control-note" data-i18n-skip>'+adoptionText('실행에 동의하면 Office에서 이 업무를 반복합니다. 기존 플랫폼의 예약은 직접 중지하세요. 그대로 두면 양쪽에서 실행될 수 있습니다.','Approving execution enables recurring work in Office. Stop the original platform schedule yourself; leaving it active can run the work in both places.')+'</p>';}
function mountWorkAdoptionPanel(d){const panel=app.querySelector('.control-panel');if(!panel)return;app.querySelector('#office-work-adoption')?.remove();app.querySelector('#office-work-migration-notice')?.remove();panel.insertAdjacentHTML('afterbegin',workMigrationNoticeHtml(d)+workAdoptionHtml(d));}
async function adoptionRun(fn){if(adoptionBusy)return;adoptionBusy=true;const panel=document.getElementById('office-work-adoption');if(panel){panel.setAttribute('aria-busy','true');panel.querySelectorAll('button').forEach(b=>b.disabled=true);panel.insertAdjacentHTML('beforeend','<div class="import-progress" role="status"><span class="busy">'+adoptionText('연결 요청 처리 중…','Processing connection request…')+'</span></div>')}try{await fn()}catch(error){setMessage(String(error.message||error))}finally{adoptionBusy=false;if(selected&&detail)renderDetail()}}
async function adoptionLoadTargets(){await adoptionRun(async()=>{const id=detail.id;setMessage(adoptionText('등록된 실행 연결을 확인하는 중…','Checking registered runtime connections…'));const data=await adoptionPost('targets',{work_id:id});if(selected!==id)return;adoptionTargets=data.targets;adoptionTargetsWork=id;if(!adoptionTargets.some(t=>t.id===adoptionChoice))adoptionChoice='';setMessage(data.targets.length?adoptionText('연결할 원본 실행을 선택하세요.','Choose the original runtime to connect.'):adoptionText('먼저 원본 실행 연결을 등록하세요.','Register the original runtime connection first.'));})}
async function adoptionBind(){await adoptionRun(async()=>{const id=detail.id,t=adoptionTargets.find(t=>t.id===adoptionChoice);if(adoptionTargetsWork!==id||!t)return;setMessage(adoptionText('원본 실행을 연결하는 중…','Connecting the original runtime…'));await adoptionPost('bind',{work_id:id,revision:detail.revision,target_work_id:t.id,target_revision:t.revision,target_fingerprint:t.fingerprint,acknowledged:true});if(selected===id)await loadDetail();setMessage(adoptionText('연결했습니다. 원본 실행의 기록과 제어를 확인할 수 있습니다.','Connected. Original execution records and controls are available here.'));})}
async function adoptionAction(action,extra={}){await adoptionRun(async()=>{const id=detail.id,a=detail.adoption;if(!a)return;setMessage(adoptionText('원본 실행에 요청하는 중…','Requesting the original runtime…'));await adoptionPost('action',{work_id:id,revision:detail.revision,binding_revision:a.binding_revision,target_revision:a.target_revision,action,...extra});if(action==='send'){adoptionDraft='';adoptionCost=false;adoptionRequestId=null}if(selected===id)await loadDetail();setMessage(adoptionText('원본 실행의 응답을 반영했습니다.','Updated with the original runtime response.'));})}
app.addEventListener('click',event=>{if(event.target.closest('#adoption-targets'))adoptionLoadTargets();if(event.target.closest('#adoption-bind'))adoptionBind();const action=event.target.closest('[data-adoption-action]');if(action)adoptionAction(action.dataset.adoptionAction);const option=event.target.closest('[data-adoption-option]');if(option)adoptionAction('permission',{permission_id:detail.adoption.snapshot.permission.id,option_id:option.dataset.adoptionOption});if(event.target.closest('#adoption-send')){if(adoptionDraft.trim().length<3||!adoptionCost)return;adoptionRequestId??=crypto.randomUUID();adoptionAction('send',{request_id:adoptionRequestId,instruction:adoptionDraft.trim(),cost_acknowledged:true})}});
app.addEventListener('change',event=>{if(event.target.id==='adoption-target'){adoptionChoice=event.target.value;document.getElementById('adoption-bind').disabled=!adoptionChoice||adoptionBusy}if(event.target.id==='adoption-cost'){adoptionCost=event.target.checked;document.getElementById('adoption-send').disabled=!adoptionCost||adoptionBusy}});
app.addEventListener('input',event=>{if(event.target.id==='adoption-instruction'){adoptionDraft=event.target.value;adoptionRequestId=null}});
`;}
