import {helpDialogHtml,helpScript,langButtonHtml,sidebarHtml,uiCss} from './ui-shell.js';
import {i18nScript} from './i18n.js';
export function workHtml(nonce:string){return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Agent Office · 업무 현황</title>
<style>${uiCss}
.top .tools{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.top input[type=search]{width:220px;font:12.5px var(--mono)}
.seg{display:inline-flex;gap:2px}.seg button{border:0;border-bottom:2px solid transparent;border-radius:0;background:none;color:var(--dim);padding:5px 9px;font:500 11px var(--mono);letter-spacing:.14em;text-transform:uppercase}.seg button[aria-pressed=true]{color:var(--text);border-bottom-color:var(--accent)}
.intake{background:var(--panel);border:1px solid var(--line);border-radius:var(--r);padding:12px;margin-bottom:20px}.intake>label:first-child{position:absolute;left:-9999px}
.intake-row{display:flex;gap:8px;align-items:center}.intake-row input{flex:1;min-width:0;padding:9px 12px;font:14px var(--mono);border-color:var(--line)}.intake-opts{display:flex;justify-content:space-between;align-items:center;gap:8px;margin-top:8px;flex-wrap:wrap}
.guided{display:inline-block;margin:0;font-size:12px}.import-link{border:0;background:none;color:var(--dim);font-size:12px;padding:2px 4px}.import-link:hover{color:var(--text)}
.group{margin-bottom:18px}.ghead{display:flex;align-items:baseline;gap:8px;font:600 13px var(--mono);padding:4px 2px 9px;border-bottom:1px solid var(--line);margin:0 0 4px}.ghead .n{color:var(--dim);font-weight:400;font-size:12px}
.g-attention{color:var(--human)}.g-active{color:var(--accent)}.g-waiting{color:var(--dim)}.g-done{color:var(--dim)}
.rows{display:flex;flex-direction:column}
.tile{display:grid;grid-template-columns:10px minmax(0,1fr) auto auto 64px;align-items:center;gap:12px;width:100%;text-align:left;background:none;border:0;border-bottom:1px solid var(--line);border-radius:0;padding:10px 6px;font:14px var(--sans);white-space:normal}
.tile:hover{background:var(--panel)}.tile strong{font-weight:500;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--text)}.tile .meta{font:12px var(--mono);color:var(--dim);white-space:nowrap}.tile .meta.time{text-align:right;color:var(--faint)}.tile .pk{display:none}
.kanban{display:grid;grid-template-columns:repeat(4,minmax(230px,1fr));gap:14px;overflow-x:auto;padding-bottom:4px}.col{min-height:120px}.col .ghead{margin-bottom:12px}
.col .tile{display:flex;flex-direction:column;align-items:stretch;gap:8px;background:var(--panel);border:1px solid var(--line);border-radius:var(--r);margin-bottom:10px;padding:13px 14px}.col .tile:hover{border-color:var(--line2);background:var(--raise)}
.col .tile .dot{display:none}.col .tile .pk{display:flex;align-items:baseline;gap:8px;font:12.5px var(--mono);color:var(--text)}.col .tile .pk .id{margin-left:auto;color:var(--faint);font-size:11.5px}
.col .tile strong{white-space:normal;font:600 14.5px/1.4 var(--sans)}.col .tile .badge{align-self:flex-start}.col .tile .meta{display:inline}.col .tile .foot{display:flex;gap:10px;font:11.5px var(--mono);color:var(--dim)}.col .tile .foot .time{margin-left:auto;color:var(--faint)}.tile .foot{display:contents}
.empty{border:1px dashed var(--line2);border-radius:var(--r);padding:22px;color:var(--dim);text-align:center;font:13px var(--mono)}
.back{border:0;background:none;color:var(--dim);padding:0;margin-bottom:14px;font-size:13px}.back:hover{color:var(--text)}
.eyebrow{font:500 10.5px var(--mono);letter-spacing:.14em;text-transform:uppercase;color:var(--dim)}
.work-head{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:6px 18px;align-items:start}.work-head h2{font:600 22px var(--sans);margin:6px 0 0;overflow-wrap:anywhere}
.runid{grid-column:2;grid-row:1/3;text-align:right;font:600 28px var(--mono);color:var(--accent);letter-spacing:-.02em;line-height:1}.runid small{display:block;font:11.5px var(--mono);color:var(--dim);letter-spacing:0;margin-top:6px}
.state{display:inline-block;font:500 11.5px var(--mono);color:var(--accent);border:1px solid currentColor;border-radius:6px;padding:1px 8px;width:max-content}.state.attention{color:var(--human)}
.reqbox{grid-column:1/-1;display:flex;gap:12px;align-items:center;background:var(--panel);border:1px solid var(--line);border-radius:var(--r);padding:11px 12px;margin-top:10px}.reqbox .who{white-space:nowrap;background:var(--raise);border-radius:6px;padding:3px 10px;font:12.5px var(--mono);color:var(--text)}
.request{margin:0;font:14px var(--mono);color:var(--text);opacity:.9;overflow-wrap:anywhere;flex:1;min-width:0}
.packline{grid-column:1/-1;display:flex;align-items:center;gap:10px;flex-wrap:wrap;margin:4px 0 0 14px;font:12.5px var(--mono);color:var(--dim)}.pill{font:500 12.5px var(--mono);color:var(--accent);border:1px solid var(--accent);background:var(--acc-a);border-radius:999px;padding:1px 10px}
.checks-wrap{grid-column:1/-1;margin:2px 0 0 14px;font:12px var(--mono);color:var(--dim)}.checks-wrap summary{cursor:pointer}.checks{display:flex;flex-wrap:wrap;gap:6px;margin-top:8px}.check{font:11.5px var(--mono);color:var(--dim);border:1px solid var(--line);border-radius:6px;padding:2px 8px}
.panel>p.muted,.panel>small{font-size:12px;display:block;margin-top:10px}
.layout{display:grid;grid-template-columns:minmax(280px,.85fr) minmax(320px,1.15fr);gap:22px;margin-top:22px;align-items:start}.panel{min-width:0}.panel>.eyebrow{display:none}.panel h3{margin:0 0 12px}
.trace-panel{background:none;border:0;padding:0}.trace-panel h3{font:600 13px var(--sans);color:var(--dim)}
.metrics{display:flex;justify-content:space-between;align-items:baseline;gap:10px;font-family:var(--mono)}.metrics b{font:600 20px var(--mono)}.rail{height:3px;background:var(--line);border-radius:3px;overflow:hidden;margin:10px 0 6px}.rail i{display:block;height:100%;background:var(--accent)}
.steps{display:flex;flex-direction:column;margin-top:16px}
.step{position:relative;display:grid;grid-template-columns:22px minmax(0,1fr);column-gap:14px;width:100%;text-align:left;background:none;border:0;border-radius:0;padding:0 0 18px;white-space:normal;font-family:var(--mono);--c:var(--line2)}
.step::before{content:"";position:absolute;left:10.5px;top:22px;bottom:0;width:1.5px;background:var(--line2)}.step:last-child::before{display:none}
.step .num{grid-row:1/4;width:22px;height:22px;border-radius:50%;border:1.5px solid var(--c);background:var(--bg);display:grid;place-items:center;font:600 10px var(--mono);color:var(--dim);position:relative;z-index:1}
.step.t-done{--c:var(--accent)}.step.t-done::before{background:var(--accent)}.step.t-done .num{color:transparent}.step.t-done .num::after,.step.t-cur .num::after,.step.t-hu .num::after{content:"";position:absolute;width:10px;height:10px;border-radius:50%;background:var(--c)}
.step.t-cur{--c:var(--accent)}.step.t-cur .num,.step.t-hu .num{color:transparent;box-shadow:0 0 0 4px color-mix(in srgb,var(--c) 22%,transparent)}.step.t-hu{--c:var(--human)}.step.t-ok{--c:var(--ok)}
.step strong{font:500 15px var(--mono);line-height:22px;color:var(--text)}.step.t-pend strong{color:var(--faint)}.step small{display:block;font:12.5px var(--mono);color:var(--dim);overflow-wrap:anywhere}.step.t-hu small:first-of-type{color:var(--human)}
.step.selected strong,.step:hover strong{color:var(--accent)}.step.selected strong{text-decoration:underline;text-underline-offset:5px;text-decoration-thickness:2px}
.step[data-verified="true"] strong{color:var(--text)}
.pack{display:flex;justify-content:space-between;gap:8px;font:12px var(--mono);border-top:1px solid var(--line);margin-top:6px;padding-top:10px}
.control-panel{border:1.5px solid var(--human)}.control-panel h3{color:var(--human)}
.controls{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:10px}.control-note{font:12px var(--mono);color:var(--dim);border-left:2px solid var(--human);padding-left:9px;margin:8px 0}
.editor label{color:var(--text);font:500 13px var(--mono)}.editor small{display:block;margin:4px 0 8px}
.runlist{border-top:1px solid var(--line);margin-top:12px;padding-top:8px;font-size:13px}.runlist summary{cursor:pointer;color:var(--dim);font:12.5px var(--mono)}.runlist ol{padding-left:18px;margin:6px 0}
.questions{margin:10px 0}.question{padding:8px 0;border-top:1px solid var(--line)}.question b{display:block;margin-bottom:6px;font-weight:500}.question input{margin-top:6px}
.jev-setting{border-top:1px solid var(--line);margin-top:12px;padding-top:10px}.jev-setting p{font-size:12px;color:var(--dim);margin:4px 0}.jev-setting label{margin:6px 0}.cost-line{color:var(--accent)!important;font-size:12px}
.jev-recommendation{border:1px solid var(--line);border-radius:8px;padding:8px 10px;margin:6px 0;overflow-wrap:anywhere}.jev-recommendation p{margin:4px 0;font-size:13px}
.importer{background:var(--panel);border:1px solid var(--line);border-radius:var(--r);padding:16px;margin-bottom:18px}.import-top{display:flex;justify-content:space-between;align-items:center;gap:10px}.import-top h2{font:600 16px var(--mono)}
.import-routes{display:flex;gap:6px;flex-wrap:wrap;margin:12px 0}.import-routes button[aria-pressed="true"]{border-color:var(--accent);color:var(--accent);background:var(--acc-a)}
.import-pane .row,.import-preview .row{display:flex;gap:8px;flex-wrap:wrap;margin-top:8px}.import-preview{border-top:1px solid var(--line);margin-top:12px;padding-top:12px}.import-preview h3{margin-bottom:6px}.import-preview ul{padding-left:18px}.import-preview details{margin:8px 0;color:var(--dim)}
.coding-dialog{border-top:1px solid var(--line);margin-top:12px;padding-top:10px}.coding-dialog .coding-session{display:block;border:1px solid var(--line);border-radius:8px;padding:8px;margin:6px 0;color:var(--text);overflow-wrap:anywhere}
.coding-turn{border:1px solid var(--line);border-radius:8px;padding:10px;margin:8px 0;overflow-wrap:anywhere}.coding-turn h5{margin:0 0 4px;font-family:var(--mono)}.coding-answer{margin-top:6px;padding:8px;background:var(--raise);border-radius:6px}.coding-dialog pre{margin:4px 0 0;white-space:pre-wrap;overflow-wrap:anywhere;font:inherit}
.coding-meta{font:11px var(--mono);color:var(--faint);overflow-wrap:anywhere}.coding-actions{display:flex;gap:6px;flex-wrap:wrap;margin-top:8px}.coding-reconcile{border-left:2px solid var(--human);padding-left:8px;margin-top:8px;overflow-wrap:anywhere}
@media(max-width:900px){.layout{grid-template-columns:1fr}.kanban{grid-template-columns:repeat(4,minmax(220px,86%))}}
@media(max-width:560px){.tile{grid-template-columns:10px minmax(0,1fr) auto}.tile .meta{display:none}.top input[type=search]{width:100%}.intake-row{flex-direction:column;align-items:stretch}.top .tools{width:100%}.runid{grid-column:1/-1;grid-row:auto;text-align:left}}</style></head><body><div class="app">${sidebarHtml('work')}<main class="main"><header class="top"><h1 id="page-title">전체 업무</h1><div class="tools"><input id="search" type="search" maxlength="200" placeholder="업무 검색" aria-label="업무 검색"><div class="seg" role="group" aria-label="보기 방식"><button type="button" data-layout="list" aria-pressed="true">목록</button><button type="button" data-layout="board" aria-pressed="false">보드</button></div></div>${langButtonHtml}</header><form id="intake" class="intake"><label for="prompt">새 업무 맡기기</label><div class="intake-row"><input id="prompt" name="prompt" maxlength="8000" required placeholder="한 줄로 어떤 업무를 맡길까요?"><button id="submit-work" class="primary" type="submit">업무 접수</button></div><div class="intake-opts"><label class="guided"><input id="guided" type="checkbox"> 심화 · 결과에 중요한 조건을 먼저 선택</label><button class="import-link" id="open-import" type="button">기존 업무 가져오기</button></div></form><section id="importer" class="importer" hidden><div class="import-top"><div><div class="eyebrow">IMPORT WORK</div><h2>기존 업무 가져오기</h2></div><button id="close-import" type="button">닫기</button></div><div class="import-routes" role="group" aria-label="가져오기 방법"><button type="button" data-import-route="external" aria-pressed="true">다른 AI의 자동화</button><button type="button" data-import-route="workflow" aria-pressed="false">워크플로 프로젝트</button><button type="button" data-import-route="bot" aria-pressed="false">기존 봇 개선</button></div><div id="import-external" class="import-pane"><p class="muted">아래 프롬프트를 기존 AI에 붙여넣고, 받은 JSON을 여기에 넣으세요. 기존 자동화는 변경하지 않습니다.</p><label for="migration-prompt">복사용 프롬프트</label><textarea id="migration-prompt" readonly aria-label="복사용 프롬프트"></textarea><div class="row"><button id="copy-migration-prompt" type="button">프롬프트 복사</button></div><label for="import-json">기존 AI의 답변</label><textarea id="import-json" maxlength="65536" placeholder="JSON 답변을 붙여넣으세요"></textarea><div class="row"><button id="paste-import" class="primary" type="button">초안 확인</button></div></div><div id="import-project" class="import-pane" hidden><p class="muted">선택한 로컬·WSL 경로의 파일 일부를 읽기 전용으로 분석합니다. AI 연결이 승인돼 있으면 README 요약과 근거 위치를 해당 모델에 보낼 수 있습니다. 이 단계에서 Jev는 호출하지 않습니다.</p><label for="import-path">프로젝트 경로</label><input id="import-path" maxlength="2048" placeholder="예: /home/me/projects/my-bot 또는 C:\\projects\\my-bot"><div class="row"><button id="scan-import" class="primary" type="button">프로젝트 살펴보기</button></div></div><section id="import-preview" class="import-preview" hidden aria-live="polite"></section></section><div id="app"><p class="muted keep">업무 불러오는 중…</p></div><div id="message" class="notice" role="status" aria-live="polite"></div></main></div>${helpDialogHtml}
<script nonce="${nonce}">
${i18nScript}
${helpScript}
let board=null,detail=null,selected=new URL(location.href).searchParams.get('work'),editing=null,draft='',loading=false,refreshQueued=false,importOpen=false,importRoute='external',importResult=null,importFromScan=false,importBusy=false,codingBusy=false,codingDraft='',attachProjectRef='',attachSessionId='',codingCatalog=null,codingCatalogProject='',attachRequestId=null,codingTurnRequestId=null,codingReconcileResult=null;
const app=document.getElementById('app'),message=document.getElementById('message'),intake=document.getElementById('intake'),importer=document.getElementById('importer'),importPreview=document.getElementById('import-preview');let pendingRequestId=null;const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={defining:'업무 정의 중',needs_model:'AI 연결 필요',awaiting_details:'선택 필요',ready:'실행 대기',running:'진행 중',queued:'전달 대기',advising:'답변 검토 중',waiting_user:'사용자 지시 대기',stopped:'종료',uncertain:'결과 확인 필요',paused:'일시정지됨',needs_human:'사람 확인 필요',waiting_auth:'로그인 필요',completed:'실행 완료',succeeded:'실행 완료',failed:'실패',reconciliation_required:'중단 지점 확인 필요',partial_evidence:'근거 부족',retryable_failure:'재시도 대기',pending:'대기',leased:'작업 중',draft_ready:'초안 준비',waiting_approval:'승인 대기'};
const active=s=>['running','leased','defining'].includes(s),attention=s=>['needs_human','needs_model','awaiting_details','failed','waiting_auth','partial_evidence','retryable_failure','waiting_approval','reconciliation_required'].includes(s);
function setMessage(value){message.textContent=value||''}
function updateConnection(){const count=board?.auth_attention_count||0;document.getElementById('connections').textContent=count?'사이트 로그인 '+count+'개 필요':'사이트 로그인'}
function showBoard(){selected=null;detail=null;editing=null;history.replaceState(null,'',location.pathname);render()}
function openWork(id){jevCostAcknowledged=false;selected=id;detail=null;editing=null;importOpen=false;codingDraft='';attachProjectRef='';attachSessionId='';codingCatalog=null;codingCatalogProject='';codingReconcileResult=null;attachRequestId=null;codingTurnRequestId=null;history.replaceState(null,'','?work='+encodeURIComponent(id));render();loadDetail()}
const groups=[['attention','확인 필요'],['active','진행 중'],['waiting','대기'],['done','종료된 업무']],viewTitles={all:'전체 업무',attention:'확인 필요',active:'진행 중',waiting:'대기',done:'종료된 업무'};
let view=new URL(location.href).searchParams.get('view')||'all',layout='board',query='',aiDataApproved=null,jevCostAcknowledged=false;try{layout=localStorage.getItem('office-layout')==='list'?'list':'board'}catch{}
if(!viewTitles[view])view='all';
function groupOf(s){if(attention(s))return 'attention';if(active(s)||['queued','advising'].includes(s))return 'active';if(['completed','succeeded','stopped'].includes(s))return 'done';return 'waiting'}
function tone(s){return s==='failed'?'err':s==='stopped'?'idle':({attention:'warn',active:'run',waiting:'idle',done:'ok'})[groupOf(s)]}
function kindLabel(w){return w.run?.kind==='swarm'?'Swarm':['coding','coding_dialog'].includes(w.run?.kind)?'코딩 업무':w.run?.kind==='pack'?'Task Pack':'접수됨'}
function ago(value){const t=Date.parse(value);if(!t)return '';const m=Math.round((Date.now()-t)/60000);return m<1?'방금':m<60?m+'분 전':m<1440?Math.round(m/60)+'시간 전':Math.round(m/1440)+'일 전'}
function tileHtml(w){return '<button type="button" class="tile '+tone(w.status)+'" data-work="'+esc(w.id)+'"><span class="dot"></span><span class="pk">'+esc(w.pack||kindLabel(w))+'<span class="id">#'+esc(String(w.id).slice(0,4))+'</span></span><strong>'+esc(w.title)+'</strong><span class="badge '+tone(w.status)+'">'+esc(labels[w.status]||w.status)+'</span><span class="foot"><span class="meta">'+esc(kindLabel(w))+'</span><span class="meta time">'+esc(ago(w.updated_at))+'</span></span></button>'}
function updateNav(){const rows=board?.works||[],counts={all:rows.length};for(const [id] of groups)counts[id]=rows.filter(w=>groupOf(w.status)===id).length;document.querySelectorAll('[data-count]').forEach(n=>n.textContent=counts[n.dataset.count]||'');document.querySelectorAll('[data-view]').forEach(n=>n.classList.toggle('on',!selected&&!importOpen&&n.dataset.view===view));document.querySelector('[data-nav="import"]')?.classList.toggle('on',importOpen);document.getElementById('page-title').textContent=selected?'업무 상세':importOpen?'가져오기':viewTitles[view];document.querySelectorAll('[data-layout]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.layout===layout)));document.querySelector('.top .tools').hidden=Boolean(selected)||importOpen}
function renderBoard(){updateConnection();updateNav();const all=board?.works||[],q=query.trim().toLowerCase(),rows=all.filter(w=>(view==='all'||groupOf(w.status)===view)&&(!q||String(w.title).toLowerCase().includes(q)));
const shown=groups.filter(([id])=>view==='all'||id===view).map(([id,name])=>({id,name,items:rows.filter(w=>groupOf(w.status)===id)}));
if(!all.length){app.innerHTML='<div class="empty">아직 맡긴 업무가 없습니다. 연결된 에이전트에게 한 줄로 요청하세요.</div>'}
else if(!rows.length){app.innerHTML='<div class="empty">조건에 맞는 업무가 없습니다.</div>'}
else if(layout==='board'){app.innerHTML='<div class="kanban">'+shown.map(g=>'<section class="col"><h3 class="ghead g-'+g.id+'">'+g.name+' <span class="n">'+g.items.length+'</span></h3>'+g.items.map(tileHtml).join('')+'</section>').join('')+'</div>'}
else{app.innerHTML=shown.filter(g=>g.items.length).map(g=>'<section class="group"><h3 class="ghead g-'+g.id+'">'+g.name+' <span class="n">'+g.items.length+'</span></h3><div class="rows">'+g.items.map(tileHtml).join('')+'</div></section>').join('')}
app.querySelectorAll('[data-work]').forEach(button=>button.onclick=()=>openWork(button.dataset.work))}
function setView(next){view=next;selected=null;detail=null;importOpen=false;importResult=null;history.replaceState(null,'',next==='all'?location.pathname:'?view='+next);render()}
function renderCodingAttach(info){const refs=info.registered_project_refs||[],project=attachProjectRef||info.suggested_project_ref||'',matches=codingCatalog&&codingCatalogProject===project,sessions=matches?codingCatalog.sessions||[]:[];
return '<section class="coding-dialog" aria-label="Codex 세션 연결"><h4>기존 Codex 대화 이어받기</h4><p class="muted">등록된 프로젝트의 기존 Codex 세션을 직접 선택하세요. 연결하면 이 Work의 코딩 경로가 시작되지만, 실제 코딩은 다음 지시를 보낼 때까지 시작되지 않습니다.</p><label for="coding-project-ref">등록된 프로젝트</label><select id="coding-project-ref"><option value="">선택해 주세요</option>'+refs.map(ref=>'<option value="'+esc(ref)+'" '+(project===ref?'selected':'')+'>'+esc(ref)+'</option>').join('')+'</select>'+(refs.length?'':'<p class="control-note">연결된 에이전트에게 로컬 Git 경로를 알려주고 runtime-config.json의 coding.projects 등록을 요청하세요. 이 화면에서는 등록된 프로젝트만 선택할 수 있습니다.</p>')+'<div class="coding-actions"><button type="button" id="coding-list-sessions" '+(refs.length?'':'disabled')+'>이 프로젝트의 세션 보기</button></div>'+(matches?'<div role="radiogroup" aria-label="연결할 Codex 세션">'+sessions.map(session=>'<label class="coding-session"><input type="radio" name="coding-session" value="'+esc(session.id)+'" '+(attachSessionId===session.id?'checked':'')+' '+(session.selectable?'':'disabled')+'><strong>'+esc(session.title||session.id)+'</strong><br><small>'+esc(session.preview||'내용 미리보기 없음')+'</small><br><small>'+esc(session.status||'상태 미확인')+' · '+esc(session.id)+'</small></label>').join('')+'</div>':'<p class="muted">세션 목록을 먼저 확인해 주세요. 다른 프로젝트 세션은 여기에 나타나지 않습니다.</p>')+(matches&&!sessions.length?'<p class="control-note">이 프로젝트에서 이어받을 수 있는 Codex 세션이 없습니다. 먼저 Codex CLI에서 한 번 대화를 시작해 주세요.</p>':'')+'<div class="coding-actions"><button type="button" class="primary" id="coding-attach" '+(matches&&attachSessionId?'':'disabled')+'>프로젝트와 세션을 연결해 Work 시작</button></div></section>';
}
function renderCodingConversation(dialog){const turns=dialog.turns||[],status=labels[dialog.status]||dialog.status;
return '<section class="coding-dialog" aria-label="Codex 대화"><h4>Codex와 주고받은 작업</h4><p class="coding-meta">프로젝트 '+esc(dialog.project_ref)+' · 세션 '+esc(dialog.session_id||'세션 확인 필요')+' · 모델 '+esc(dialog.model)+' · '+esc(status)+'</p><p class="muted">Codex가 실제 코딩을 맡습니다. 상위 에이전트의 조언은 답변과 구분해 보여줍니다. 다음 작업은 새 지시를 보낼 때만 시작합니다.</p>'+turns.map(turn=>'<article class="coding-turn"><h5>지시 '+(turn.ordinal+1)+' · '+esc(labels[turn.status]||turn.status)+'</h5><pre>'+esc(turn.instruction)+'</pre>'+(turn.reply!==null?'<div class="coding-answer"><b>Codex 답변</b>'+(turn.reply_redacted?'<small class="muted"> · 비밀값 가림</small>':'')+'<pre>'+esc(turn.reply)+'</pre></div>':'<p class="muted">Codex의 완료 답변이 아직 없습니다.</p>')+(turn.advice!==null?'<div class="coding-answer"><b>상위 에이전트 조언</b><pre>'+esc(turn.advice)+'</pre></div>':turn.reply!==null&&turn.advice_at?'<p class="muted">상위 에이전트 조언은 제공되지 않았습니다. Codex 답변은 보존했습니다.</p>':'')+(turn.reason?'<p class="coding-reconcile">'+esc(turn.reason)+'</p>':'')+'<div class="coding-meta">'+esc(turn.model||dialog.model)+' · '+esc(turn.session_id||dialog.session_id||'세션 확인 필요')+' · '+esc(turn.completed_at||turn.created_at)+'</div></article>').join('')+(turns.length?'':'<p class="muted">아직 보낸 지시가 없습니다.</p>')+(dialog.can_turn?'<div class="editor"><label for="coding-followup">Codex에 다음 지시</label><textarea id="coding-followup" maxlength="4000" placeholder="예: 방금 변경한 파일의 테스트 결과를 확인하고 남은 문제를 설명해줘">'+esc(codingDraft)+'</textarea><small>Codex의 답변을 확인한 뒤, 한 번에 한 지시만 보냅니다.</small><button type="button" id="coding-send" class="primary">Codex에 지시 보내기</button></div>':'<p class="control-note">'+(dialog.needs_reconcile?'결과가 불확실합니다. Git과 세션 상태를 확인하기 전에는 같은 지시를 다시 실행하지 않습니다.':dialog.status==='stopped'?'이 대화는 종료됐습니다.':'이전 지시의 결과를 기다리는 중입니다. 자동으로 다음 지시를 보내지 않습니다.')+'</p>')+'<div class="coding-actions">'+(dialog.can_stop?'<button type="button" id="coding-stop" class="warning">이 대화 중단</button>':'')+(dialog.needs_reconcile?'<button type="button" id="coding-reconcile">중단 지점 확인</button>':'')+'</div>'+(codingReconcileResult?'<div class="coding-reconcile"><b>확인 결과 · 자동 재실행 없음</b><pre>'+esc(JSON.stringify(codingReconcileResult,null,2))+'</pre></div>':'')+'</section>';
}
function renderCodingRecovery(dialog){
if(!dialog.needs_reconcile||!codingReconcileResult?.observed_git)return '';
const git=codingReconcileResult.observed_git;
return '<div class="coding-reconcile"><h4>중단 지점 검토 후 재개</h4><p>같은 지시를 다시 실행하지 않습니다. Codex 세션과 현재 Git 변경을 직접 확인한 뒤, 지금 상태를 다음 지시의 기준으로 삼을 수 있습니다.</p><p class="coding-meta">현재 HEAD '+esc(git.head)+'<br>변경 지문 '+esc(git.state_sha256)+'</p><label><input type="checkbox" id="coding-git-reviewed"> 현재 Git 변경을 검토했습니다</label><label><input type="checkbox" id="coding-session-reviewed"> Codex 세션의 마지막 결과를 검토했습니다</label><div class="coding-actions"><button type="button" id="coding-accept-reconciliation" class="warning">현재 상태를 기준으로 다시 지시하기</button></div></div>';
}
function renderDetail(){updateConnection();if(!detail){app.innerHTML='<button type="button" class="back" id="back">← 업무 목록</button><p class="muted">업무 읽는 중…</p>';document.getElementById('back').onclick=showBoard;return}const d=detail,p=d.spec,checks=p?.completion_checks||[],percent=d.progress_percent,control=d.control,pauseControl=control?.can_pause?control:d.work_control?.can_pause?d.work_control:null,selectedStage=d.stages.find(s=>s.id===editing),runStatus=d.run_status||d.work_status||'unobserved';
const effect={read_only:'read-only',draft:'draft only',external_change:'change after approval'}[p?.requested_effect]||p?.requested_effect||'';
const head='<button type="button" class="back" id="back">← 업무 목록</button><section class="work-head"><span class="state '+(attention(runStatus)?'attention':'')+'">'+esc(labels[runStatus]||runStatus)+'</span><div class="runid"><span class="eyebrow" style="display:block;margin-bottom:6px">work</span>#'+esc(d.id.slice(0,8).toUpperCase())+'<small>'+(d.run_id?'run #'+esc(d.run_id.slice(0,8).toUpperCase()):'run not started')+'</small></div><h2>'+esc(d.title)+'</h2><div class="reqbox"><span class="who">'+esc(d.client||'mcp')+'</span><p class="request">'+esc(d.prompt||d.goal)+'</p><span class="caret" aria-hidden="true"></span></div>'+((d.pack||p?.route?.pack_family)?'<div class="packline"><span>pack</span><span class="pill">'+esc(d.pack||p.route.pack_family)+'</span><span>'+esc(effect)+'</span></div>':'')+(checks.length?'<details class="checks-wrap"><summary>완료 조건 '+checks.length+'개</summary><div class="checks">'+checks.map(c=>'<span class="check" title="'+esc(c.evidence)+'">완료 조건 · '+esc(c.result)+'</span>').join('')+'</div></details>':'')+'</section>';
const trace=s=>s.verified?'t-done':['running','leased','defining'].includes(s.status)?'t-cur':attention(s.status)?'t-hu':'t-pend';
const left='<section class="panel trace-panel"><div class="eyebrow">CURRENT LOOP</div><h3>진행 단계</h3><div class="metrics"><div><b>'+(percent===null?'—':percent+'%')+'</b><div class="muted">단계 진척도</div></div><small class="muted">'+(d.swarm||d.coding?esc(d.verified_steps+' / '+d.total_steps+' 단계 · '+d.agent_count+'명 작업 중'):'단계별 확인 미지원')+'</small></div><div class="rail" role="progressbar" aria-label="단계 진척도" aria-valuemin="0" aria-valuemax="100" '+(percent===null?'':'aria-valuenow="'+percent+'"')+'><i style="width:'+(percent??0)+'%"></i></div><small class="muted">'+esc(d.progress_basis)+'</small><div class="steps">'+d.stages.map((s,i)=>'<button type="button" class="step '+trace(s)+' '+(s.id===editing?'selected':'')+'" data-stage="'+esc(s.id)+'" data-verified="'+s.verified+'"><span class="num">'+String(i+1).padStart(2,'0')+'</span><strong>'+esc(s.label)+' · '+esc(labels[s.status]||s.status)+'</strong><small>'+esc(s.objective)+'</small><small>'+esc(s.owner?'현재 담당: '+s.owner:s.executor?'실행기: '+s.executor:'아직 배정되지 않음')+'</small></button>').join('')+'</div><div class="pack"><span class="muted">선택된 Pack</span><strong>'+esc(d.pack||'아직 선택되지 않음')+'</strong></div></section>';
const question=p&&d.work_status==='awaiting_details'?'<div class="questions"><div class="eyebrow">WORK DEFINITION</div><h3>업무 조건 선택</h3>'+d.questions.map(q=>'<div class="question" data-question="'+esc(q.id)+'"><b>'+esc(q.prompt)+'</b><select><option value="">선택해 주세요</option>'+q.options.map(o=>'<option value="'+esc(o.id)+'" '+(o.id===q.recommended_id?'selected':'')+'>'+esc(o.label)+'</option>').join('')+'<option value="custom">직접 입력</option></select><input aria-label="직접 입력" maxlength="800" placeholder="직접 입력" hidden></div>').join('')+'<button type="button" class="primary" id="answer">선택 저장</button></div>':'';
const buttons=d.coding_dialog?'':pauseControl?'<button type="button" id="pause" class="'+(pauseControl.paused?'primary':'warning')+'">'+(pauseControl.paused?'작업 재개':'일시정지')+'</button>':'<button type="button" disabled>일시정지 미지원</button>';
const editor=d.coding_dialog?'':selectedStage?.can_edit?'<div class="editor"><label for="instruction">'+esc(selectedStage.label)+' 단계에 새 지침</label><textarea id="instruction" maxlength="2000" placeholder="예: 결과를 요약문으로 정리해줘"></textarea><small>'+(d.coding?'아직 시작하지 않은 단계의 지침만 바뀝니다. 담당 CLI와 쓰기 범위는 유지됩니다.':'시작하지 않은 읽기 전용 단계에만 적용됩니다. 이미 검증한 결과는 보존됩니다.')+'</small><button type="button" class="primary" id="save">다음 배정에 적용</button></div>':'<p class="control-note">'+(d.swarm?'지침은 아직 시작하지 않은 읽기 전용 단계를 선택하면 바꿀 수 있습니다.':d.coding?'이미 시작한 단계는 지침을 바꿀 수 없습니다. 다음 실행 전에 일시정지할 수 있습니다.':'이 실행 경로는 안전한 중간 수정·정지를 지원하지 않습니다. 다음 실행 지침은 연결된 에이전트에서 수정하세요.')+'</p>';
const retry=d.work_status==='needs_model'?(aiDataApproved===false?'<p class="control-note">업무 내용을 AI로 보내는 허용이 필요합니다. 허용하면 선택한 AI가 이 업무를 정의합니다.</p><button type="button" id="allow-ai-data" class="primary">AI 전송 허용 후 재시도</button> ':'<p class="control-note">AI 연결을 확인한 뒤 같은 업무를 다시 정의할 수 있습니다.</p>')+'<button type="button" id="retry-define">업무 정의 재시도</button>':'';
const handoffs=d.client_handoffs?.length?'<details class="runlist"><summary>클라이언트 인계 '+d.client_handoffs.length+'건</summary><ol>'+d.client_handoffs.map(h=>'<li>'+esc(h.source)+' → '+esc(h.target||'미배정')+' · '+esc(h.reason)+' · '+esc(h.status==='transferred'?'이어받음':'영향 확인 필요')+'<small> · '+esc(h.target_model||h.source_model)+'</small></li>').join('')+'</ol></details>':'';
const jev=d.jev?'<div class="jev-setting"><h4>Jev 판단</h4><p>선택사항입니다. 꺼도 AI와 코드로 업무를 진행할 수 있습니다.</p>'+renderJevRecommendations(d.jev_recommendations,d.jev_recommendation_status)+(d.jev.enabled?'<button type="button" id="jev-toggle" '+(d.jev.can_change?'':'disabled')+'>Jev 끄기</button>':'<p class="cost-line">켜면 Jev API 사용 비용이 발생할 수 있습니다.</p><label><input id="jev-cost" type="checkbox" '+(d.jev.can_change?'':'disabled')+' '+(jevCostAcknowledged&&d.jev.can_change?'checked':'')+'>API 비용 가능성을 확인했습니다</label><button type="button" id="jev-toggle" '+(jevCostAcknowledged&&d.jev.can_change?'':'disabled')+'>Jev 켜기</button>')+(d.jev.can_change?'':'<p>이 상태에서는 설정을 바꿀 수 없습니다.</p>')+'</div>':'';
const ci=d.imported_coding,codingActions=ci&&!d.coding_dialog?'<div class="jev-setting"><h4>고정 계획 방식</h4><p>대상: '+esc(ci.project_ref||'미등록')+' · 코드 수정 권한 '+(ci.allow_write?'있음':'없음')+' · AI 자료 사용 '+(ci.model_data_approved?'승인됨':'승인 필요')+'</p><p class="muted">'+esc(ci.project_path)+'</p>'+(ci.can_start?'<p>계획 만들기를 누르면 이 프로젝트에 인계 문서가 저장됩니다. 코드 수정 단계는 별도로 실행합니다.</p><button type="button" id="coding-plan" class="primary">구현 계획 만들기</button>':'')+(ci.can_step?'<p>다음 단계: '+esc(ci.next_stage.actor)+' · '+esc(ci.next_stage.operation)+'. 실행하면 프로젝트 코드가 바뀔 수 있습니다. 한 번에 한 단계씩 진행합니다.</p><button type="button" id="coding-next" class="primary">다음 단계 실행</button>':'')+(ci.blocker?'<p class="control-note">'+esc(ci.blocker)+'</p>':'')+'</div>':' ';
const codingAttach=d.coding_attach?.eligible?renderCodingAttach(d.coding_attach):'',codingConversation=d.coding_dialog?renderCodingConversation(d.coding_dialog)+(d.coding_dialog.older_turns_available?'<p class="muted">최근 20개 지시만 표시합니다. 이전 기록은 로컬 업무 기록에 보존되어 있습니다.</p>':'')+renderCodingRecovery(d.coding_dialog):'';
const plan=d.imported_plan,planSource=typeof plan?.source==='string'?plan.source:plan?.source?.name||plan?.source?.platform||plan?.source?.path||'출처 미확인';
const imported=plan?'<details class="runlist"><summary>가져온 계획 · '+esc(plan.kind||'초안')+'</summary><p class="muted">'+esc(planSource)+' · '+(plan.verified?'검증됨':'원본 별도 확인 필요')+'</p>'+(plan.steps?.length?'<ol>'+plan.steps.slice(0,20).map(step=>'<li>'+esc(step.goal)+' <small>· '+esc(step.effect||'효과 미확인')+(step.depends_on?.length?' · 선행: '+esc(step.depends_on.join(', ')):'')+'</small></li>').join('')+'</ol>':'<p class="muted">확인된 단계가 없습니다.</p>')+(plan.unknowns?.length?'<p class="muted">미확인: '+esc(plan.unknowns.slice(0,8).map(item=>typeof item==='string'?item:item.field||'항목').join(', '))+'</p>':'')+'</details>':'';
const right='<section class="panel control-panel"><div class="eyebrow">WORK CONTROL</div><h3>작업 제어</h3><div class="controls">'+buttons+'</div>'+retry+question+editor+codingAttach+codingConversation+codingActions+jev+imported+handoffs+(d.events?.length?'<details class="runlist"><summary>최근 변경 '+d.events.length+'건</summary><ol>'+d.events.map(e=>'<li>'+esc(e.kind)+' · '+esc(e.detail)+'</li>').join('')+'</ol></details>':'')+'<details class="runlist"><summary>실행 이력 '+d.runs.length+'건</summary><ol>'+d.runs.map(r=>'<li>'+esc(r.source_kind)+' · '+esc(r.created_at)+'</li>').join('')+'</ol></details><p class="muted">'+esc(d.completion_note)+'</p></section>';
app.innerHTML=head+'<div class="layout">'+left+right+'</div><div class="tagline"><span>agent-office · local stdio mcp</span><span>proposal is not permission · snapshot approval · independent readback</span></div>';document.getElementById('back').onclick=showBoard;app.querySelectorAll('[data-stage]').forEach(button=>button.onclick=()=>{const next=d.stages.find(s=>s.id===button.dataset.stage);if(!next?.can_edit){setMessage('이 단계는 지금 수정할 수 없습니다.');return}editing=next.id;draft='';renderDetail();document.getElementById('instruction')?.focus()});document.getElementById('pause')?.addEventListener('click',()=>control?.can_pause?act(control.paused?'resume':'pause'):pauseWork(!d.work_control.paused));document.getElementById('save')?.addEventListener('click',()=>{const value=document.getElementById('instruction').value.trim();if(!value){setMessage('새 지침을 입력해 주세요.');return}act('edit',editing,value)});const textarea=document.getElementById('instruction');if(textarea){textarea.value=draft;textarea.oninput=()=>draft=textarea.value}document.getElementById('answer')?.addEventListener('click',answer);app.querySelectorAll('[data-question]').forEach(node=>{const choice=node.querySelector('select'),input=node.querySelector('input');choice.onchange=()=>input.hidden=choice.value!=='custom'});if(typeof compactHints==='function')compactHints(app)}
function render(){intake.hidden=Boolean(selected)||importOpen;importer.hidden=Boolean(selected)||!importOpen;updateNav();if(selected)renderDetail();else if(importOpen){app.innerHTML='';compactHints(importer)}else renderBoard()}
function importField(value){return value&&typeof value==='object'&&!Array.isArray(value)?value.value??value.text??null:value}
function importItem(value){return typeof value==='string'?value:importField(value?.title)||importField(value?.description)||importField(value?.goal)||importField(value?.name)||'항목'}
function renderJevRecommendations(items,status){
const suggestions=Array.isArray(items)?items:[],shape={choice:'보기 중 하나 고르기',yes_no:'예/아니오 확인',score:'정도 비교'};
if(!suggestions.length){const reason=status==='not_approved'?'AI의 프로젝트 자료 사용이 승인되지 않아 연결 지점을 분석하지 않았습니다.':status==='model_unavailable'?'AI 분석을 마치지 못해 연결 지점을 추천하지 않았습니다.':status==='unsupported_evidence'?'읽은 코드에서 판단 지점의 근거를 찾지 못했습니다.':status==='complete'?'읽은 코드에서 Jev에 적합하다고 설명할 수 있는 지점을 확인하지 못했습니다.':'연결 지점은 아직 분석되지 않았습니다.';return '<p class="muted">Jev 추천 없음 · '+esc(reason)+'</p>'}
return '<div class="jev-recommendations"><h4>Jev가 도움이 될 수 있는 지점</h4>'+suggestions.map(item=>'<article class="jev-recommendation"><p class="muted">단계: '+esc(item.step_goal||item.step_id||'미확인')+'</p><p><b>'+esc(item.judgment)+'</b> · '+esc(shape[item.answer_shape]||'짧은 판단')+'</p><p>왜 Jev일까요? '+esc(item.why_fit)+'</p><p class="muted">코드가 자료와 후보를 준비하고 실제 클릭·저장·결과 확인을 맡습니다. Jev는 그 사이의 짧은 판단만 제안합니다.</p><p class="muted">근거: '+esc((item.evidence||[]).map(ref=>ref.file+':'+ref.line).join(', ')||'위치 미확인')+'</p></article>').join('')+'<p class="muted">읽기 전용 분석에서 나온 제안입니다. 실제 반복 빈도·정답률·속도 이득은 아직 검증되지 않았습니다. Work에서 Jev를 켜도 이 후보 단계에 자동으로 삽입되지는 않습니다.</p></div>';
}
function setImportRoute(route){importRoute=route;document.querySelectorAll('[data-import-route]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.importRoute===route)));document.getElementById('import-external').hidden=route!=='external';document.getElementById('import-project').hidden=route==='external';document.getElementById('scan-import').textContent=route==='bot'?'봇 프로젝트 살펴보기':'프로젝트 살펴보기';importResult=null;importPreview.hidden=true}
function renderImportPreview(){if(!importResult){importPreview.hidden=true;return}const p=importResult.preview?.draft||importResult.preview||{},analysis=p.analysis&&typeof p.analysis==='object'?p.analysis:null,body=analysis||p,scan=importFromScan,kind=p.kind||importResult.kind||'unknown',bot=kind==='bot_only',completion=Array.isArray(body.completion)?body.completion.map(c=>importField(c.result)||importItem(c)).filter(Boolean):[],unknowns=[...(Array.isArray(p.unknowns)?p.unknowns:[]),...(Array.isArray(analysis?.unknowns)?analysis.unknowns:[])],evidence=Array.isArray(p.evidence)?p.evidence:Array.isArray(analysis?.evidence)?analysis.evidence:[],steps=Array.isArray(body.steps)?body.steps:[],recommendations=Array.isArray(p.recommendations)?p.recommendations:Array.isArray(analysis?.recommendations)?analysis.recommendations:[];
const observedGoal=importField(body.goal)||importField(p.purpose)||'',goal=bot?recommendations[0]||observedGoal||'기존 봇 동작을 유지하면서 새 기능을 구현한다':observedGoal;
const list=(values,limit)=>values.length?'<ul>'+values.slice(0,limit).map(value=>'<li>'+esc(value)+'</li>').join('')+'</ul>':'<p class="muted">아직 확인되지 않았습니다.</p>';
const missing='<p class="muted">미확인 '+unknowns.length+'건</p>'+(unknowns.length?list(unknowns.map(item=>typeof item==='string'?item:(item.field||'항목')+' · '+(item.reason||'확인 필요')),8):'');
const source=evidence.length?'<details><summary>근거 '+evidence.length+'건 보기</summary>'+list(evidence.map(item=>(item.source_ref||item.path||(item.file?item.file+':'+item.line:'출처 미확인'))+' · '+(item.quote||item.summary||item.description||'')),8)+'</details>':'';
const choices=scan?'<div class="cost-note"><label><input id="import-jev" type="checkbox">이 Work에서 Jev 사용</label><p class="cost-line">Jev는 선택사항입니다. 켜면 API 비용이 발생할 수 있습니다. 끄면 AI와 코드 경로를 사용합니다.</p><label id="import-cost-line" hidden><input id="import-cost" type="checkbox">Jev API 비용 가능성을 확인하고 연결에 동의합니다</label></div>':'';
const trigger=body.trigger?.kind&&body.trigger.kind!=='unknown'?[body.trigger.kind,body.trigger.rule,body.trigger.timezone].filter(Boolean).join(' · '):'미확인',delivery=body.delivery?.channel&&body.delivery.channel!=='unknown'?[body.delivery.channel,body.delivery.target].filter(Boolean).join(' · '):'미확인',approval=importField(body.approval_boundary),sourceName=p.source?.name||p.source?.platform||p.path||'프로젝트';
const metadata='<p class="muted">원본: '+esc(sourceName)+' · 시작: '+esc(trigger)+' · 전달: '+esc(delivery)+'</p>'+(approval?'<p class="muted">승인 경계: '+esc(approval)+'</p>':'');
const completionDefault=completion.reduce((value,item)=>{const next=value?value+' / '+item:item;return next.length<=500?next:value},'')||String(completion[0]||'').slice(0,500);
const completionNotes=completion.length>1?'<details><summary>확인된 완료 조건 '+completion.length+'개</summary>'+list(completion,12)+'</details>':'';
importPreview.hidden=false;importPreview.innerHTML='<div class="eyebrow">REVIEW FIRST</div><h3>'+(bot?'봇 개선 제안':scan?'프로젝트 이전 초안':'자동화 이전 초안')+'</h3><p class="muted">'+(scan?bot?'현재 봇의 기능은 유지합니다. 구현을 선택해도 프로젝트 등록·권한 확인 전에는 코드를 수정하지 않습니다.':'읽기 전용 스캔 결과입니다. 확인 전에는 프로젝트 코드와 일정이 바뀌지 않습니다.':'기존 AI가 알려준 내용으로 만든 미검증 초안입니다. 기존 자동화는 그대로 둡니다.')+'</p>'+metadata+'<label for="import-goal">새 Work의 목표</label><input id="import-goal" maxlength="2000" value="'+esc(goal)+'" placeholder="이 업무가 달성해야 할 결과"><label for="import-completion">완료 조건</label><textarea id="import-completion" rows="3" maxlength="500" placeholder="한 회차가 끝났음을 어떻게 확인할까요?">'+esc(completionDefault)+'</textarea><p class="muted">확인된 단계 '+steps.length+'개 · 제안 '+recommendations.length+'개</p>'+(steps.length?list(steps.map(item=>importItem(item)),8):'')+completionNotes+(recommendations.length?'<h4>추가할 수 있는 기능</h4>'+list(recommendations.map(importItem),8):'')+missing+source+(scan?renderJevRecommendations(p.jev_recommendations,p.analysis_status):'')+choices+'<div class="row"><button type="button" class="primary" id="accept-import">'+(bot?'개선 Work 만들기':'Work 초안 저장')+'</button></div><p class="muted">'+(bot?'개선용 업무 초안을 만듭니다. 실제 프로젝트 수정은 상세 화면에서 단계마다 시작합니다.':'저장해도 곧바로 실행되거나 일정이 켜지지 않습니다.')+'</p>';
document.getElementById('import-jev')?.addEventListener('change',event=>{document.getElementById('import-cost-line').hidden=!event.target.checked;if(!event.target.checked)document.getElementById('import-cost').checked=false});
document.getElementById('accept-import').onclick=acceptImport;if(typeof compactHints==='function')compactHints(importPreview);
}
async function importRequest(endpoint,payload){if(importBusy)return;importBusy=true;setMessage('가져올 내용을 확인하는 중…');try{const response=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json','x-agent-driver':'human-office'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw Error(data.error||'가져오기 실패');importResult=data;importFromScan=endpoint==='work/import/scan';renderImportPreview();setMessage(importFromScan?'프로젝트 분석을 마쳤습니다. 목표와 완료 조건, 비용 선택을 확인해 주세요.':'이전 초안을 만들었습니다. 근거와 미확인 항목을 확인해 주세요.')}catch(error){setMessage(String(error.message||error))}finally{importBusy=false}}
async function acceptImport(){if(!importResult?.import_id||importBusy)return;const goal=document.getElementById('import-goal').value.trim(),completion=document.getElementById('import-completion').value.trim(),jev_enabled=Boolean(document.getElementById('import-jev')?.checked),cost_acknowledged=Boolean(document.getElementById('import-cost')?.checked),kind=importResult.preview?.kind||importResult.kind,mode=kind==='bot_only'?'augment':'migrate';if(!goal||!completion){setMessage('목표와 완료 조건을 입력해 주세요.');return}if(jev_enabled&&!cost_acknowledged){setMessage('Jev API 비용 가능성을 확인해 주세요.');return}importBusy=true;setMessage('Work 초안을 저장하는 중…');try{const response=await fetch('work/import/accept',{method:'POST',headers:{'content-type':'application/json','x-agent-driver':'human-office'},body:JSON.stringify({import_id:importResult.import_id,goal,completion,mode,jev_enabled,cost_acknowledged})});const data=await response.json();if(!response.ok)throw Error(data.error||'Work 저장 실패');importResult=null;openWork(data.work_id);setMessage(mode==='augment'?'개선용 업무 초안을 만들었습니다. 프로젝트 변경 전 등록과 권한 확인이 필요합니다.':'Work 초안을 저장했습니다. 실행이나 일정은 아직 시작되지 않았습니다.')}catch(error){setMessage(String(error.message||error))}finally{importBusy=false}}
async function submitWork(event){event.preventDefault();const prompt=document.getElementById('prompt').value.trim();if(!prompt){setMessage('업무를 한 줄로 입력해 주세요.');return}const button=document.getElementById('submit-work');button.disabled=true;pendingRequestId??=crypto.randomUUID();setMessage('업무를 접수하고 정의하는 중…');try{const res=await fetch('work/start',{method:'POST',headers:{'content-type':'application/json','x-agent-driver':'human-office'},body:JSON.stringify({request_id:pendingRequestId,prompt,intake_mode:document.getElementById('guided').checked?'guided':'quick'})});const data=await res.json();if(!res.ok)throw Error(data.error||'업무 접수 실패');pendingRequestId=null;document.getElementById('prompt').value='';openWork(data.work_id);setMessage(data.status==='needs_model'?'업무는 저장됐습니다. AI 연결을 확인한 뒤 다시 정의할 수 있습니다.':data.status==='awaiting_details'?'업무 조건을 선택해 주세요.':'업무를 접수했습니다. 실행 배정은 연결된 에이전트가 이어갑니다.')}catch(error){setMessage(String(error.message||error))}finally{button.disabled=false}}
async function loadDetail(){if(!selected||loading){refreshQueued=true;return}loading=true;const id=selected;try{const res=await fetch('work/detail?id='+encodeURIComponent(id),{cache:'no-store'});if(!res.ok)throw Error('업무 상세를 읽지 못했습니다.');const fresh=await res.json();if(id===selected){detail=fresh;if(!['instruction','coding-followup','coding-project-ref'].includes(document.activeElement?.id))renderDetail()}}catch(error){setMessage(String(error.message||error))}finally{loading=false;if(refreshQueued){refreshQueued=false;loadDetail()}}}
async function act(action,worker_id,instruction){if(!detail?.control||!detail.run_id)return;setMessage('적용 중…');try{const res=await fetch('office/action',{method:'POST',headers:{'content-type':'application/json','x-agent-driver':'human-office'},body:JSON.stringify({run_id:detail.run_id,action,revision:detail.control.revision,worker_id,instruction})});const data=await res.json();if(!res.ok)throw Error(data.error||'변경 실패');editing=null;draft='';await loadDetail();setMessage(action==='edit'?'새 지침이 다음 배정에 적용됩니다.':action==='pause'?'새 배정을 멈췄습니다.':'작업을 다시 진행합니다.')}catch(error){setMessage(String(error.message||error))}}
async function pauseWork(paused){if(!detail?.work_control)return;setMessage('적용 중…');try{const res=await fetch('work/pause',{method:'POST',headers:{'content-type':'application/json','x-agent-driver':'human-office'},body:JSON.stringify({work_id:detail.id,revision:detail.work_control.revision,paused})});const data=await res.json();if(!res.ok)throw Error(data.error||'변경 실패');await loadDetail();setMessage(paused?'다음 실행을 멈췄습니다.':'다음 실행을 허용합니다.')}catch(error){setMessage(String(error.message||error))}}
async function retryDefine(){if(!detail)return;setMessage('업무를 다시 정의하는 중…');try{const res=await fetch('work/define',{method:'POST',headers:{'content-type':'application/json','x-agent-driver':'human-office'},body:JSON.stringify({work_id:detail.id})});const data=await res.json();if(!res.ok)throw Error(data.error||'재시도 실패');await loadDetail();setMessage(data.status==='needs_model'?'AI 연결을 확인해 주세요. 업무는 저장돼 있습니다.':'업무 정의를 갱신했습니다.')}catch(error){setMessage(String(error.message||error))}}
async function toggleWorkJev(){if(!detail?.jev?.can_change)return;const enabled=!detail.jev.enabled,cost_acknowledged=enabled&&Boolean(document.getElementById('jev-cost')?.checked);if(enabled&&!cost_acknowledged){setMessage('Jev API 비용 가능성을 확인해 주세요.');return}setMessage('Jev 설정을 저장하는 중…');try{const response=await fetch('work/jev',{method:'POST',headers:{'content-type':'application/json','x-agent-driver':'human-office'},body:JSON.stringify({work_id:detail.id,revision:detail.revision,enabled,cost_acknowledged})});const data=await response.json();if(!response.ok)throw Error(data.error||'Jev 설정 실패');jevCostAcknowledged=false;await loadDetail();setMessage(enabled?'이 Work에서 Jev를 켰습니다. API 비용이 발생할 수 있습니다.':'이 Work에서 Jev를 껐습니다.')}catch(error){setMessage(String(error.message||error))}}
async function importedCodingAction(kind){if(codingBusy||!detail?.imported_coding)return;const ci=detail.imported_coding;if(kind==='start'&&!ci.can_start||kind==='step'&&!ci.can_step)return;codingBusy=true;const endpoint=kind==='start'?'work/import/coding/start':'work/import/coding/step',payload=kind==='start'?{work_id:detail.id}:{work_id:detail.id,run_id:ci.run_id,expected_revision:ci.run_revision};setMessage(kind==='start'?'구현 계획을 만드는 중…':'다음 코딩 단계를 실행하는 중…');document.getElementById(kind==='start'?'coding-plan':'coding-next').disabled=true;try{const response=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json','x-agent-driver':'human-office'},body:JSON.stringify(payload)}),data=await response.json();if(!response.ok)throw Error(data.error||'코딩 단계 실패');await loadDetail();setMessage(kind==='start'?'계획이 준비됐습니다. 각 단계를 확인하고 실행해 주세요.':'한 단계를 마쳤습니다. 결과를 확인한 뒤 다음 단계를 실행할 수 있습니다.')}catch(error){await loadDetail();setMessage(String(error.message||error))}finally{codingBusy=false}}
async function codingPost(endpoint,payload){const response=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json','x-agent-driver':'human-office'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw Error(data.error||'Codex 대화 변경 실패');return data}
async function loadCodingSessions(){if(codingBusy||!detail?.coding_attach?.eligible)return;const project=document.getElementById('coding-project-ref')?.value.trim()||'';if(!project){setMessage('등록된 프로젝트 이름을 입력해 주세요.');return}codingBusy=true;attachProjectRef=project;attachSessionId='';attachRequestId=null;codingCatalog=null;codingCatalogProject='';setMessage('이 프로젝트의 Codex 세션을 확인하는 중…');try{const response=await fetch('work/coding/sessions?project_ref='+encodeURIComponent(project),{cache:'no-store'}),data=await response.json();if(!response.ok)throw Error(data.error||'Codex 세션을 읽지 못했습니다.');codingCatalog=data;codingCatalogProject=project;renderDetail();setMessage('연결할 기존 세션을 직접 선택해 주세요. 같은 세션을 다른 Codex 창에서 동시에 사용하지 마세요.')}catch(error){renderDetail();setMessage(String(error.message||error))}finally{codingBusy=false}}
async function attachCodingSession(){if(codingBusy||!detail?.coding_attach?.eligible||!attachSessionId||!codingCatalog||codingCatalogProject!==attachProjectRef)return;codingBusy=true;attachRequestId??=crypto.randomUUID();setMessage('선택한 Codex 세션을 이 업무에 연결하는 중…');try{await codingPost('work/coding/attach',{work_id:detail.id,project_ref:attachProjectRef,session_id:attachSessionId,request_id:attachRequestId});attachRequestId=null;await loadDetail();setMessage('Codex 대화가 연결됐습니다. 다음 지시를 보내면 코딩이 시작됩니다.')}catch(error){setMessage(String(error.message||error))}finally{codingBusy=false}}
async function sendCodingInstruction(){const dialog=detail?.coding_dialog;if(codingBusy||!dialog?.can_turn)return;const instruction=document.getElementById('coding-followup')?.value.trim()||'';if(instruction.length<3){setMessage('Codex에 보낼 지시를 입력해 주세요.');return}codingBusy=true;codingDraft=instruction;codingTurnRequestId??=crypto.randomUUID();setMessage('Codex에 지시를 전달하는 중…');try{await codingPost('work/coding/turn',{dialog_id:dialog.id,expected_revision:dialog.revision,request_id:codingTurnRequestId,instruction});codingTurnRequestId=null;codingDraft='';await loadDetail();setMessage('Codex가 작업 중입니다. 답변이 저장되면 여기에 표시됩니다.')}catch(error){setMessage(String(error.message||error))}finally{codingBusy=false}}
async function stopCodingConversation(){const dialog=detail?.coding_dialog;if(codingBusy||!dialog?.can_stop)return;codingBusy=true;setMessage('대화 중단을 요청하는 중…');try{await codingPost('work/coding/stop',{dialog_id:dialog.id,expected_revision:dialog.revision});await loadDetail();setMessage('대화 중단을 요청했습니다. 실행 중이던 변경은 확인이 필요할 수 있습니다.')}catch(error){setMessage(String(error.message||error))}finally{codingBusy=false}}
async function reconcileCodingConversation(){const dialog=detail?.coding_dialog;if(codingBusy||!dialog?.needs_reconcile)return;codingBusy=true;setMessage('세션과 Git 상태를 읽기 전용으로 확인하는 중…');try{codingReconcileResult=await codingPost('work/coding/reconcile',{dialog_id:dialog.id});renderDetail();setMessage('확인 결과를 표시했습니다. 같은 지시를 자동으로 다시 보내지 않습니다.')}catch(error){setMessage(String(error.message||error))}finally{codingBusy=false}}
async function acceptCodingReconciliation(){
const dialog=detail?.coding_dialog,observed=codingReconcileResult?.observed_git;
if(codingBusy||!dialog?.needs_reconcile||!observed)return;
if(!document.getElementById('coding-git-reviewed')?.checked||!document.getElementById('coding-session-reviewed')?.checked){setMessage('현재 Git 변경과 Codex 세션을 각각 확인해 주세요.');return}
codingBusy=true;setMessage('검토한 상태를 새 기준으로 저장하는 중…');
try{await codingPost('work/coding/reconcile',{dialog_id:dialog.id,action:'accept_current_git',expected_revision:dialog.revision,observed_git_head:observed.head,observed_git_state_sha256:observed.state_sha256,confirm_git_reviewed:true,confirm_session_reviewed:true});codingReconcileResult=null;await loadDetail();setMessage('현재 상태를 기준으로 저장했습니다. 새 지시를 보내기 전까지 실행하지 않습니다.')}
catch(error){setMessage(String(error.message||error))}finally{codingBusy=false}
}
app.addEventListener('click',event=>{if(event.target.closest('#allow-ai-data'))allowAiData();if(event.target.closest('#retry-define'))retryDefine();if(event.target.closest('#jev-toggle'))toggleWorkJev();if(event.target.closest('#coding-plan'))importedCodingAction('start');if(event.target.closest('#coding-next'))importedCodingAction('step');if(event.target.closest('#coding-list-sessions'))loadCodingSessions();if(event.target.closest('#coding-attach'))attachCodingSession();if(event.target.closest('#coding-send'))sendCodingInstruction();if(event.target.closest('#coding-stop'))stopCodingConversation();if(event.target.closest('#coding-reconcile'))reconcileCodingConversation();if(event.target.closest('#coding-accept-reconciliation'))acceptCodingReconciliation()});
app.addEventListener('change',event=>{if(event.target.id==='jev-cost'){jevCostAcknowledged=Boolean(detail?.jev?.can_change&&event.target.checked);const button=document.getElementById('jev-toggle');if(button)button.disabled=!detail?.jev?.can_change||!event.target.checked}if(event.target.id==='coding-project-ref'){attachProjectRef=event.target.value.trim();attachSessionId='';attachRequestId=null;codingCatalog=null;codingCatalogProject='';renderDetail()}if(event.target.name==='coding-session'){attachSessionId=event.target.value;attachRequestId=null;renderDetail()}});
app.addEventListener('input',event=>{if(event.target.id==='coding-followup')codingDraft=event.target.value;if(event.target.id==='coding-project-ref'&&event.target.value.trim()!==codingCatalogProject){attachSessionId='';document.getElementById('coding-attach').disabled=true}});
document.getElementById('open-import').onclick=()=>{importOpen=true;render();setImportRoute('external');loadMigrationPrompt()};
document.getElementById('close-import').onclick=()=>{importOpen=false;importResult=null;render();setMessage('')};
document.querySelectorAll('[data-import-route]').forEach(button=>button.onclick=()=>{setImportRoute(button.dataset.importRoute);if(button.dataset.importRoute==='external')loadMigrationPrompt()});
async function loadMigrationPrompt(){const target=document.getElementById('migration-prompt');if(target.value)return;try{const response=await fetch('work/import/prompt',{cache:'no-store'});if(!response.ok)throw Error('이전 프롬프트를 읽지 못했습니다.');const body=await response.text();let data;try{data=JSON.parse(body)}catch{data=body}const prompt=typeof data==='string'?data:data.prompt;if(typeof prompt!=='string'||!prompt.trim())throw Error('이전 프롬프트가 비어 있습니다.');target.value=prompt}catch(error){setMessage(String(error.message||error))}}
document.getElementById('copy-migration-prompt').onclick=async()=>{const target=document.getElementById('migration-prompt');if(!target.value)await loadMigrationPrompt();if(!target.value)return;try{await navigator.clipboard.writeText(target.value);setMessage('프롬프트를 복사했습니다. 기존 AI에 붙여넣으세요.')}catch{target.select();setMessage('프롬프트를 선택했습니다. 복사해서 기존 AI에 붙여넣으세요.')}};
document.getElementById('paste-import').onclick=()=>{const text=document.getElementById('import-json').value.trim();if(!text){setMessage('기존 AI의 JSON 답변을 붙여넣어 주세요.');return}importRequest('work/import/paste',{text})};
document.getElementById('scan-import').onclick=()=>{const path=document.getElementById('import-path').value.trim();if(!path){setMessage('로컬 또는 WSL 프로젝트 경로를 입력해 주세요.');return}importRequest('work/import/scan',{path})};
async function answer(){if(!detail)return;const answers={};for(const node of app.querySelectorAll('[data-question]')){const id=node.dataset.question,choice=node.querySelector('select').value,value=choice==='custom'?node.querySelector('input').value.trim():choice;if(value)answers[id]=value}try{const res=await fetch('work/answer',{method:'POST',headers:{'content-type':'application/json','x-agent-driver':'human-office'},body:JSON.stringify({work_id:detail.id,revision:detail.revision,answers})});const data=await res.json();if(!res.ok)throw Error(data.error||'저장 실패');await loadDetail();setMessage(data.status==='needs_model'?'답변을 저장했습니다. AI 연결을 확인한 뒤 업무 정의를 재개해 주세요.':'선택을 반영했습니다. 실행 배정은 연결된 에이전트가 이어갑니다.')}catch(error){setMessage(String(error.message||error))}}
async function loadAiConsent(){try{const r=await fetch('settings/status',{cache:'no-store'});if(r.ok){const v=await r.json();aiDataApproved=v.work_model_data?.editable===false?null:Boolean(v.work_model_data?.approved);if(selected&&detail?.work_status==='needs_model')renderDetail()}}catch{}}
async function allowAiData(){setMessage('AI 전송을 허용하는 중…');try{const r=await fetch('settings/work-data',{method:'POST',headers:{'content-type':'application/json','x-agent-driver':'human-settings'},body:JSON.stringify({approved:true})});const v=await r.json();if(!r.ok)throw Error(v.error||'허용 실패');aiDataApproved=true;await retryDefine()}catch(error){setMessage(String(error.message||error))}}
document.querySelectorAll('[data-view]').forEach(link=>link.addEventListener('click',event=>{event.preventDefault();setView(link.dataset.view)}));
document.querySelector('[data-nav="import"]').addEventListener('click',event=>{event.preventDefault();selected=null;detail=null;document.getElementById('open-import').click()});
document.querySelectorAll('[data-layout]').forEach(button=>button.onclick=()=>{layout=button.dataset.layout;try{localStorage.setItem('office-layout',layout)}catch{}renderBoard()});
document.getElementById('search').addEventListener('input',event=>{query=event.target.value;renderBoard()});
compactHints(importer);loadAiConsent();if(new URL(location.href).searchParams.get('import')==='1'&&!selected)document.getElementById('open-import').click();
intake.addEventListener('submit',submitWork);fetch('work/board',{cache:'no-store'}).then(r=>r.json()).then(data=>{board=data;render();if(selected)loadDetail()}).catch(e=>setMessage(String(e.message||e)));const stream=new EventSource('work/events');stream.addEventListener('board',event=>{const next=JSON.parse(event.data),old=board?.works.find(w=>w.id===selected),now=next.works.find(w=>w.id===selected);board=next;if(!selected){if(importOpen)updateNav();else renderBoard()}else if(JSON.stringify(old)!==JSON.stringify(now))loadDetail()});stream.onerror=()=>setMessage('실시간 연결을 다시 시도하는 중입니다.');document.addEventListener('visibilitychange',()=>{if(!document.hidden&&selected)loadDetail()});
</script></body></html>`;}
