/** Contextual approval/results only. There is no separate file-manager navigation. */
export function workFileScript(){return String.raw`
let fileActionBusy=false;
function fileWorkPanel(work){
  const report=work.file_activity;if(!report)return '';
  const folders=report.requests.filter(r=>r.granted).map(r=>'<div class="coding-turn"><h4>접근 중인 폴더</h4><p>'+esc(r.granted_path||r.path||'')+'</p><small>이 폴더 권한은 다른 업무에서도 재사용됩니다. 해제해도 이미 남긴 실행 기록은 보존됩니다.</small><button data-file-revoke="'+esc(r.id)+'">폴더 접근 해제</button></div>').join('');
  const requests=report.requests.filter(r=>!r.granted).map(r=>'<div class="coding-turn"><h4>이 업무에 필요한 폴더 접근</h4><p>'+esc(r.purpose)+'</p><label>폴더 경로<input data-file-path="'+esc(r.id)+'" value="'+esc(r.path||'')+'" placeholder="런타임이 실행되는 컴퓨터의 폴더 경로"></label>'+(r.read_content?'<label><input type="checkbox" data-file-content="'+esc(r.id)+'"> 작은 텍스트의 내용 일부도 읽기</label><p class="muted">허용한 내용은 연결된 에이전트에게 전달될 수 있습니다.</p>':'')+(r.allow_move?'<label><input type="checkbox" data-file-move="'+esc(r.id)+'"> 정리안을 따로 승인한 후 이동 허용</label>':'')+'<button data-file-grant="'+esc(r.id)+'" '+(work.paused?'disabled':'')+'>이 폴더 접근 허용</button></div>').join('');
  const plans=report.plans.map(p=>'<div class="coding-turn"><h4>'+esc({preview:'정리안 확인',applying:'이동 결과 확인 중',done:'파일 이동 완료',undoing:'복원 결과 확인 중',undone:'원래 위치로 복원',needs_review:'파일 상태 확인 필요'}[p.state]||p.state)+'</h4>'+p.moves.map(m=>'<p>'+esc(m.from)+' → '+esc(m.to)+'</p><small>'+esc(m.reason)+'</small>').join('')+(p.state==='preview'?'<button data-file-apply="'+esc(p.id)+'" '+(work.paused||!p.permission_active?'disabled':'')+'>이 정리안 승인하고 이동</button>':p.state==='done'?'<button data-file-undo="'+esc(p.id)+'" '+(work.paused||!p.permission_active?'disabled':'')+'>원래 위치로 되돌리기</button>':'')+(!p.permission_active?'<p class="muted">폴더 권한이 해제되거나 변경됐습니다. 실행 기록만 표시합니다.</p>':'')+(p.interrupted||p.state==='needs_review'?'<p>중단된 작업입니다. 원본과 대상의 상태를 확인하기 전에는 다시 실행하지 않습니다.</p>':'')+'</div>').join('');
  const observations=report.observations.map(o=>'<p>'+o.files_observed+'개 확인 · 제외 '+o.skipped_entries+'개'+(o.truncated?' · 범위 제한으로 일부만 확인':'')+'</p>'+o.preserved.map(f=>'<p class="muted">보존: '+esc(f.path)+' · '+esc({recent_file:'최근 수정',shortcut:'바로가기',application_managed:'앱·프로젝트 파일',large_file:'대용량'}[f.reason]||f.reason)+'</p>').join('')).join('');
  return '<section class="panel coding-dialog" aria-label="파일 작업 확인과 결과"><h3>파일 작업</h3>'+folders+requests+plans+observations+'<p>이동 '+report.moved.length+'개 · 원위치 복원 '+report.restored.length+'개'+(report.needs_review?' · 수동 확인 필요':'')+'</p>'+(report.history_truncated?'<p>최근 정리안 100개의 기록입니다. 위 건수는 전체 누계가 아닙니다.</p>':'')+'<small>실행한 이동·복원은 당시 파일 내용의 해시를 대조한 기록입니다. 업무 전체의 완료 여부와는 구분합니다.</small><button data-file-refresh>기록 새로고침</button></section>';
}
app.addEventListener('click',async event=>{
  const button=event.target.closest('[data-file-grant],[data-file-revoke],[data-file-apply],[data-file-undo],[data-file-refresh]');if(!button||fileActionBusy||!detail)return;
  if(button.hasAttribute('data-file-refresh')){await loadDetail();return;}
  let action,body={work_id:detail.id};const request=button.dataset.fileGrant;
  if(request){action='grant';body.request_id=request;body.path=app.querySelector('[data-file-path="'+request+'"]').value.trim();body.read_content=Boolean(app.querySelector('[data-file-content="'+request+'"]')?.checked);body.allow_move=Boolean(app.querySelector('[data-file-move="'+request+'"]')?.checked);}else if(button.dataset.fileRevoke){action='revoke';body.request_id=button.dataset.fileRevoke;}else{action=button.dataset.fileApply?'apply':'undo';body.plan_id=button.dataset.fileApply||button.dataset.fileUndo;}
  fileActionBusy=true;button.disabled=true;
  try{const response=await fetch('files/'+action,{method:'POST',headers:{'content-type':'application/json','x-agent-driver':'human-office'},body:JSON.stringify(body)});const value=await response.json();if(!response.ok)throw Error(value.error);setMessage(action==='grant'?'폴더 접근을 허용했습니다. 에이전트가 이 업무를 이어갈 수 있습니다.':action==='revoke'?'폴더 접근을 해제했습니다. 기존 실행 기록은 남아 있습니다.':value.state==='needs_review'?'일부 작업의 확인이 필요합니다. 결과를 확인하세요.':action==='undo'?'파일을 원래 위치로 복원했습니다.':'승인한 정리안을 실행했습니다.');await loadDetail();}catch(error){setMessage('파일 작업을 완료하지 못했습니다: '+error.message);}finally{fileActionBusy=false;button.disabled=false;}
});
`;}
